### ISSUE TITLE
ECMA5 getters cause requireSpaceBeforeObjectValues to error out

### ISSUE THREAD

**Issue by jeffcharles** [jscs-dev/node-jscs#1037]
When I have the following .jscs.json file:

`{"requireSpaceBeforeObjectValues": true}`

And I run jscs on the following file which contains a getter (<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get>):

```
var foo = {
	get bar() {
		return 'baz';
	}
};
```

I get the following output:

```
TypeError: Cannot read property '_tokenIndex' of undefined
    at Object.JsFile.getNextToken (D:\workspace\jscs_test\node_modules\jscs\lib\js-file.js:264:26)
    at D:\workspace\jscs_test\node_modules\jscs\lib\rules\require-space-before-object-values.js:53:37
    at Array.forEach (native)
    at D:\workspace\jscs_test\node_modules\jscs\lib\rules\require-space-before-object-values.js:43:29
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (D:\workspace\jscs_test\node_modules\jscs\lib\js-file.js:378:42)
    at Object.module.exports.check (D:\workspace\jscs_test\node_modules\jscs\lib\rules\require-space-before-object-values.js:42:14)
    at null.<anonymous> (D:\workspace\jscs_test\node_modules\jscs\lib\string-checker.js:157:22)
    at Array.forEach (native)
    at StringChecker.checkString (D:\workspace\jscs_test\node_modules\jscs\lib\string-checker.js:155:35)
```

I do not get this error when running jscs 1.10.0, but I do get it when running 1.11.0 or 1.11.1.

**Comment by mikesherov** [comment]
Thanks for contributing! This'll be fixed shortly!
