### ISSUE TITLE
config is empty Configuration.prototype.load in configuration.js

### ISSUE THREAD

**Issue by dman777** [jscs-dev/node-jscs#1072]
in `node_modules/gulp-jscs/node_modules/jscs/lib/config/configuration.js` config is emtpy in `Configuration.prototype.load = function(config) {}`. This causes:

```
[19:09:22] TypeError: Object.keys called on non-object
  at Function.keys (native)
  at Function.<anonymous> (/home/one/github/load-balancer-service/node_modules/gulp-angular-filesort/node_modules/ng-dependencies/node_modules/sugar/release/sugar-full.development.js:180:23)
  at NodeConfiguration.Configuration._throwNonCamelCaseErrorIfNeeded (/home/one/github/load-balancer-service/node_modules/gulp-jscs/node_modules/jscs/lib/config/configuration.js:416:12)
  at NodeConfiguration.Configuration.load (/home/one/github/load-balancer-service/node_modules/gulp-jscs/node_modules/jscs/lib/config/configuration.js:52:10)
  at [object Object].StringChecker.configure (/home/one/github/load-balancer-service/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:66:29)
  at [object Object].Checker.configure (/home/one/github/load-balancer-service/node_modules/gulp-jscs/node_modules/jscs/lib/checker.js:26:39)
  at module.exports (/home/one/github/load-balancer-service/node_modules/gulp-jscs/index.js:31:11)
  at Gulp.<anonymous> (/home/one/github/load-balancer-service/gulp/tasks/lint.js:16:15)
  at module.exports (/home/one/github/load-balancer-service/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/home/one/github/load-balancer-service/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/one/github/load-balancer-service/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/home/one/github/load-balancer-service/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
  at process._tickCallback (node.js:419:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:906:3
```

I am using the gulp-jscs of jscs. Please let me know if this a gulp-jscs issue instead.

**Comment by mikesherov** [comment]
I assume your configuration is set up improperly. Did you read the docs and double check you have everything set up properly? What does your code look like?

**Comment by dman777** [comment]
Perhaps this is a `gulp-jscs` issue? Or am I doing something wrong? From usage, it looks like config. is not mandatory.

https://www.npmjs.com/package/gulp-jscs

```javascript
var gulp = require('gulp');
var jscs = require('gulp-jscs');
 
gulp.task('default', function () {
    return gulp.src('src/app.js')
        .pipe(jscs());
});
```

**Comment by mikesherov** [comment]
@dman777, please ask future support questions on our Google group. 

JSCS needs either a provided config, or usage of a .jscsrc file. See http://jscs.info for more information. Thanks!
