### ISSUE TITLE
Update tree-iterator to support JSX (in newer esprima-fb)

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1131]
Looks like `esprima-fb@13001.1.0-dev-harmony-fb` updated with a `XJS -> JSX` change. https://github.com/facebook/esprima/commit/2d47a78dc50a8cce10bcef7730a0e81f7782f2d2

I guess we should update the files for this similar to #830? I don't know if we also just want to find-replace or just append?

So `XJSIdentifier` would be `JSXIdentifier`.

**Comment by zxqfox** [comment]
Can we support both?

**Comment by mdevils** [comment]
I guess we must support both.

**Comment by mikesherov** [comment]
Yeah, need to support both. @hzoo, can you whip up a PR?

**Comment by hzoo** [comment]
Yeah - got it

**Comment by kimmobrunfeldt** [comment]
I'm getting the same error "Unknown node type JSXElement". Has the fix been released yet? If not how can I use a dev version or to fix it otherwise?
I use these versions of esprima-fb and jscs:

    "esprima-fb": "13001.1.0-dev-harmony-fb",
    "jscs": "1.11.3",

Stacktrace:

    Error: Unknown node type JSXElement.
        at Controller.traverse (/Users/kbru/code/tty/board/node_modules/jscs/node_modules/estraverse/estraverse.js:515:31)
        at Object.traverse (/Users/kbru/code/tty/board/node_modules/jscs/node_modules/estraverse/estraverse.js:707:27)
        at Object.iterate (/Users/kbru/code/tty/board/node_modules/jscs/lib/tree-iterator.js:9:20)
        at Object.JsFile.iterate (/Users/kbru/code/tty/board/node_modules/jscs/lib/js-file.js:331:29)
        at Object.JsFile (/Users/kbru/code/tty/board/node_modules/jscs/lib/js-file.js:34:10)
        at StringChecker.checkString (/Users/kbru/code/tty/board/node_modules/jscs/lib/string-checker.js:139:20)
        at null.<anonymous> (/Users/kbru/code/tty/board/node_modules/jscs/lib/checker.js:40:25)
        at Array.<anonymous> (/Users/kbru/code/tty/board/node_modules/jscs/node_modules/vow/lib/vow.js:699:39)
        at Immediate.callFns [as _onImmediate] (/Users/kbru/code/tty/board/node_modules/jscs/node_modules/vow/lib/vow.js:23:35)
        at processImmediate [as _immediateCallback] (timers.js:374:17)

**Comment by kimmobrunfeldt** [comment]
As a quick fix, I reverted back to esprima-fb@12001.1.0-dev-harmony-fb.

**Comment by hzoo** [comment]
I'l look into it - but yeah there hasn't been a release since 1.11.3 was a while ago so you'll have to run it against master or the commit from the PR.

**Comment by hzoo** [comment]
I don't see any errors using the commit `d6fcbc` or `master`. You can try 

```js
  "devDependencies": {
    "esprima-fb": "~13001.1.0-dev-harmony-fb",
    "jscs": "jscs-dev/node-jscs#master"
}
```

**Comment by kimmobrunfeldt** [comment]
That worked for me too, thanks!
