### ISSUE TITLE
"undefined is not a function" when using a plugin

### ISSUE THREAD

**Issue by mzgol** [jscs-dev/node-jscs#1227]
The following `.jscsrc`:
```json
{
    "plugins": ["jscs-trailing-comma"],

    "requireTrailingCommaInExpandedLiterals": true,
    "disallowTrailingCommaInCollapsedLiterals": true
}
```
fails with the following message:
```
TypeError: undefined is not a function
    at /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/jscs-trailing-comma/lib/common/setup-rule.js:75:50
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/grunt-jscs/node_modules/jscs/lib/js-file.js:406:42)
    at checkType (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/jscs-trailing-comma/lib/common/setup-rule.js:72:22)
    at Object.rule.check (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/jscs-trailing-comma/lib/common/setup-rule.js:62:17)
    at null.<anonymous> (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:133:18)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:131:31)
    at StringChecker.checkString (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:111:14)
    at null.<anonymous> (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/grunt-jscs/node_modules/jscs/lib/checker.js:43:21)
    at Array.<anonymous> (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/grunt-jscs/node_modules/vow/lib/vow.js:699:39)
    at Immediate.callFns [as _onImmediate] (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/grunt-jscs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:361:17)
```

Tested on Node.js `0.12.2` & io.js `1.6.3`. grunt-jscs `1.6.0`, jscs `1.12.0`, jscs-trailing-comma `0.4.1`.

This worked fine with grunt-jscs `1.5.0`, jscs `1.11.3`.

**Comment by zxqfox** [comment]
https://github.com/EE/jscs-trailing-comma/blob/master/lib/common/setup-rule.js#L75-L76
```
file.getTokenPosByRangeStart(node.range[0])
```

Dup of #1214

**Comment by mikesherov** [comment]
@mzgol please use `file.getFirstNodeToken()` instead!

**Comment by mzgol** [comment]
@mikesherov Thanks, that works.
