### ISSUE TITLE
You cannot specify the same token as both token and nextToken

### ISSUE THREAD

**Issue by jdat82** [jscs-dev/node-jscs#1354]
Got this today : 

`Error running rule maximumNumberOfLines: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new`

Error: You cannot specify the same token as both token and nextToken

    at TokenAssert._validateOptions (node_modules/grunt-jscs/node_modules/jscs/lib/token-assert.js:343:15)
    at TokenAssert.linesBetween (node_modules/grunt-jscs/node_modules/jscs/lib/token-assert.js:279:10)
    at Object.module.exports.check (node_modules/grunt-jscs/node_modules/jscs/lib/rules/maximum-number-of-lines.js:38:23)
    at null.<anonymous> (node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:141:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:137:31)
    at StringChecker.checkString (node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:117:14)
    at null.<anonymous> (node_modules/grunt-jscs/node_modules/jscs/lib/checker.js:43:21)
    at Array.3 (node_modules/grunt-jscs/node_modules/vow/lib/vow.js:699:39)
    at Object.callFns [as _onImmediate] (node_modules/grunt-jscs/node_modules/vow/lib/vow.js:23:35)```

**Comment by hzoo** [comment]
Could you also post a code snippet (preferably as minimal as possible to reproduce this) and which version of jscs?

Although based on the error message it looks like this is due to the `firstToken` and `lastToken` being the same..

**Comment by zxqfox** [comment]
@jdat82 Is it was an empty file?

**Comment by hzoo** [comment]
Ok I just tested myself and made an empty file and can reproduce. So we need to just make an exception for that?

**Comment by zxqfox** [comment]
@hzoo Yeah, for sure. No reason to report empty files.

**Comment by hzoo** [comment]
Ok simplest thing would be to just do this?

```js
if (firstToken === lastToken) { return; }
```

**Comment by zxqfox** [comment]
@hzoo Well, I'm not sure we should check them at all. Not just in this rule.

@mrjoelkemp @markelog @mikesherov Guys what you think if we disable checking of empty files?

**Comment by hzoo** [comment]
haha what a better idea.

**Comment by mrjoelkemp** [comment]
@zxqfox That's what I was thinking: skipping empty files. Empty files shouldn't be forced to have a newline at EOF right?

**Comment by zxqfox** [comment]
Definitely! :smirk_cat:

**Comment by jdat82** [comment]
@zxqfox  Yes the problem is with empty files.
