### ISSUE TITLE
Empty switch statement causes TypeError: Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by hejmartin** [jscs-dev/node-jscs#1393]
When running jscs on a file that contains an empty switch statement, I get the following error;
```
TypeError: Cannot read property 'loc' of undefined
    at /Users/martin/Sites/magnet-qdp/grunt/node_modules/grunt-jscs/node_modules/jscs/lib/rules/validate-indentation.js:463:58
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/martin/Sites/magnet-qdp/grunt/node_modules/grunt-jscs/node_modules/jscs/lib/js-file.js:426:42)
    at generateIndentations (/Users/martin/Sites/magnet-qdp/grunt/node_modules/grunt-jscs/node_modules/jscs/lib/rules/validate-indentation.js:455:18)
    at Object.module.exports.check (/Users/martin/Sites/magnet-qdp/grunt/node_modules/grunt-jscs/node_modules/jscs/lib/rules/validate-indentation.js:557:9)
    at null.<anonymous> (/Users/martin/Sites/magnet-qdp/grunt/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:141:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/martin/Sites/magnet-qdp/grunt/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:137:31)
    at StringChecker.fixString (/Users/martin/Sites/magnet-qdp/grunt/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:244:22)
    at null.<anonymous> (/Users/martin/Sites/magnet-qdp/grunt/node_modules/grunt-jscs/node_modules/jscs/lib/checker.js:59:27)
```
I can recreate this issue with a file containing nothing but this:
```javascript
switch (1) {}
```
Ideally, of course I shouldn't have any empty switch statements in my code: But it took me a while to find what in a file with 300 lines of code caused the error, as the entire task crashed and only named the file it occurred in but not why or where, so a better error message here would be much welcome.

I'm using jscs 1.13.1 via grunt-jscs 1.8.0 on Mac OS X 10.10.3 running node 0.10.4

**Comment by zxqfox** [comment]
@mikesherov It's about `validateIndentation`, but ... I can't repeat it.

**Comment by hzoo** [comment]
Will make a PR to fix
