### ISSUE TITLE
Error processing rule

### ISSUE THREAD

**Issue by DanielHeath** [jscs-dev/node-jscs#1527]
```
Error running rule requirePaddingNewLinesBeforeLineComments: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'type' of undefined
    at /Users/daniel.heath/Projects/ask-izzy/ask-izzy/node_modules/jscs/lib/rules/require-padding-newlines-before-line-comments.js:100:26
    at /Users/daniel.heath/Projects/ask-izzy/ask-izzy/node_modules/jscs/lib/js-file.js:483:17
    at Array.forEach (native)
    at Object.JsFile.iterateTokensByType (/Users/daniel.heath/Projects/ask-izzy/ask-izzy/node_modules/jscs/lib/js-file.js:481:26)
    at Object.module.exports.check (/Users/daniel.heath/Projects/ask-izzy/ask-izzy/node_modules/jscs/lib/rules/require-padding-newlines-before-line-comments.js:86:14)
    at null.<anonymous> (/Users/daniel.heath/Projects/ask-izzy/ask-izzy/node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/daniel.heath/Projects/ask-izzy/ask-izzy/node_modules/jscs/lib/string-checker.js:161:31)
    at StringChecker.checkString (/Users/daniel.heath/Projects/ask-izzy/ask-izzy/node_modules/jscs/lib/string-checker.js:106:14)
    at null.<anonymous> (/Users/daniel.heath/Projects/ask-izzy/ask-izzy/node_modules/jscs/lib/checker.js:44:21) at ./webpack/prod.load.js :
     1 |
--------^
     2 |// Register babel to have ES6 support
     3 |require("babel/register");
```

The file it's failing on is:
```

// Register babel to have ES6 support
require("babel/register");
module.exports = require("./prod.config");
```

**Comment by DanielHeath** [comment]
$ ./node_modules/.bin/jscs --version
1.13.1

**Comment by DanielHeath** [comment]
I'm on OSX Mavericks

**Comment by markelog** [comment]
hm, can't repro it, could you try current master?

**Comment by hzoo** [comment]
It looks like this is the same as #1444 although doesn't seem like we can reproduce on either?

**Comment by DanielHeath** [comment]
I'd guess the issue is that the file starts with a comment, and it's trying to read the 'previous' line to check if it's blank (but there is no previous line).

**Comment by hzoo** [comment]
Ok can reproduce - not sure why it's giving an internal error. I'l try to make a fix but in the meantime you can remove the first blank line (unless that's intended)
