### ISSUE TITLE
Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by adambuczynski** [jscs-dev/node-jscs#1528]
The following error occurs in several of my files:

TypeError: Cannot read property 'loc' of undefined
    at /node_modules/gulp-jscs/node_modules/jscs/lib/rules/validate-indentation.js:463:58
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/node_modules/gulp-jscs/node_modules/jscs/lib/js-file.js:426:42)
    at generateIndentations (/node_modules/gulp-jscs/node_modules/jscs/lib/rules/validate-indentation.js:455:18)
    at Object.module.exports.check (/node_modules/gulp-jscs/node_modules/jscs/lib/rules/validate-indentation.js:557:9)
    at null.<anonymous> (/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:141:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:137:31)
    at StringChecker.checkString (/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:117:14)
    at DestroyableTransform._transform (/node_modules/gulp-jscs/index.js:72:22)

**Comment by hzoo** [comment]
Can you post your jscs version/config, and a short code snippet that results in that error?

**Comment by adambuczynski** [comment]
Certainly.

I'm using jscs via gulp-jscs 1.6.0 which seems to be using jscs 1.13.1.
I'm not passing in any specific config parameters.

The .jscsrc file looks like this:

```json
{
  "preset": "google",
  "fileExtensions": [".js"],
  "maxErrors": 100,
  "verbose": false,
  "excludeFiles": [
    "public/**",
    "node_modules/**",
    "client/vendor/**",
    "client/static/**"
  ],
  "requireParenthesesAroundIIFE": true,
  "maximumLineLength": 100,
  "validateLineBreaks": "LF",
  "validateIndentation": 2,
  "disallowMultipleVarDecl": "exceptUndefined",
  "disallowKeywordsOnNewLine": null,
  "disallowSpacesInsideObjectBrackets": null,
  "disallowImplicitTypeConversion": ["string"],
  "safeContextKeyword": "self"
}
```

One of the files that triggers the error contains the following code:

```js


/**
 * Module definition and dependencies
 */
angular.module('MKA.Activity.Search.Watchlist.Controller', [
  'MKA.Activity.Search.Watchlist.Resource'
])

/**
 * Controller
 */
.controller('ActivitySearchWatchlistCtrl', function(
  $scope, $state, $modalInstance, $filter, MKA, Watchlist, User, search
) {

  //Watchlist frequencies
  $scope.frequencies = [
    {
      hours: 24,
      label: 'Daily'
    },
    {
      hours: 48,
      label: 'Every two days'
    },
    {
      hours: 7*24,
      label: 'Every week'
    },
    {
      hours: 30*24,
      label: 'Every month'
    }
  ];

  //Watchlist model
  $scope.watchlist = new Watchlist();
  $scope.watchlist.search = search;
  $scope.watchlist.email = User.data.email;
  $scope.watchlist.frequency = $scope.frequencies[2].hours;
  $scope.watchlist.name = $filter('childLabel')(search.child) + ', ' +
              $filter('activityType')(search.activityTypeId);

  //Category?
  if (search.activityCategoryId) {
    $scope.watchlist.name += ', ' + $filter('activityCategory')(search.activityCategoryId);
  }

  //Submitted state
  $scope.submitted = false;

  /**
   * Submit watchlist subscription
   */
  $scope.subscribe = function(watchlist) {

    //Must be validated
    if ($scope.watchlistForm.$invalid) {
      return;
    }

    //Mark as submitted
    $scope.submitted = true;

    //Save
    watchlist.$save().then(function(data) {

      //Toggle submitted state
      $scope.submitted = true;

    }).catch(function(error) {

      //Handle errors
      if (error) {
        switch (error.code) {

        }
      }
    });
  };

  /**
   * Cancel modal
   */
  $scope.cancel = function() {
    $modalInstance.dismiss('cancel');
  };

  /**
   * Close modal
   */
  $scope.close = function() {
    $modalInstance.close();
  };
});

```

Running lint on this file results in:

```
Error running rule validateIndentation: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'loc' of undefined
```

**Comment by markelog** [comment]
Another `validateIndentation` bug, /cc @mikesherov

**Comment by hzoo** [comment]
This is the same as #1393 as well?
