### ISSUE TITLE
Error running jscs-dev/node-jscs version": "1.13.1"

### ISSUE THREAD

**Issue by jameswomack** [jscs-dev/node-jscs#1532]
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'jscs-jsdoc/lib/rules/validate-jsdoc'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jwomack/Projects/github/jameswomack/gulp-space/node_modules/jscs/lib/rules/jsdoc.js:799:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by jameswomack** [comment]
Temporary fix is to use `npm i jscs-jsdoc -D`

**Comment by hzoo** [comment]
Yeah `module.exports = require('jscs-jsdoc/lib/rules/validate-jsdoc');`

https://github.com/jscs-dev/node-jscs/commit/e553d4bcc03cfef232f21a8d3138d3057600151e#diff-23d81634c6375c34edb4ecf95a7beaaeR799

https://github.com/jscs-dev/node-jscs/blob/master/package.json#L87 - we need to move it to dependency not devDependency right? @markelog 

This shouldn't be an error for 1.13.1 - it would be for master though?
