### ISSUE TITLE
Error running rule disallowQuotedKeysInObjects

### ISSUE THREAD

**Issue by shauns** [jscs-dev/node-jscs#1552]
As requested by the error output, here's an issue for a problem with the `disallowQuotedKeysInObjects` rule:

```
Error running rule disallowQuotedKeysInObjects: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'type' of undefined
    at /Users/shauns/code/ff/ffnow-demo/node_modules/jscs/lib/rules/disallow-quoted-keys-in-objects.js:64:24
    at Array.forEach (native)
    at /Users/shauns/code/ff/ffnow-demo/node_modules/jscs/lib/rules/disallow-quoted-keys-in-objects.js:62:29
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/shauns/code/ff/ffnow-demo/node_modules/jscs/lib/js-file.js:426:42)
    at Object.module.exports.check (/Users/shauns/code/ff/ffnow-demo/node_modules/jscs/lib/rules/disallow-quoted-keys-in-objects.js:61:14)
    at null.<anonymous> (/Users/shauns/code/ff/ffnow-demo/node_modules/jscs/lib/string-checker.js:141:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/shauns/code/ff/ffnow-demo/node_modules/jscs/lib/string-checker.js:137:31)
    at StringChecker.checkString (/Users/shauns/code/ff/ffnow-demo/node_modules/jscs/lib/string-checker.js:117:14) at src/redux/clientMiddleware.js :
     1 |const createMiddleware = (client) => {
--------^
     2 |  return ({}) => {
     3 |    return (next) => (action) => {


1 code style error found.
```

The offending file:
```
const createMiddleware = (client) => {
  return ({}) => {
    return (next) => (action) => {
      const { promise, types, ...rest } = action;
      if (!promise) {
        return next(action);
      }

      const [REQUEST, SUCCESS, FAILURE] = types;
      next({...rest, type: REQUEST});

      return promise(client).then(
        (result) => next({...rest, result, type: SUCCESS}),
        (error) => next({...rest, error, type: FAILURE})
      );

    };
  };
};

export {createMiddleware}
```

...and my JSCS config from `package.json`

```
"jscsConfig": {
    "preset": "airbnb",
    "esprima": "./node_modules/esprima-fb",
    "fileExtensions": [
      ".js",
      ".jsx"
    ]
  },
```

This is with v1.13.1

Let me know if any further info will help --

**Comment by mrjoelkemp** [comment]
Thanks for reporting @shauns. Would you be open to trying out [babel-jscs](https://github.com/jscs-dev/babel-jscs) as a replacement for (now deprecated) esprima-fb? You'll likely need to use the latest master of jscs as well. Let me know if that fixes the issue.

**Comment by shauns** [comment]
Thanks @mrjoelkemp -- that resolves the error (still have a bunch of style warnings though ;) )

For future reference. package.json dependencies:
```
"jscs": "jscs-dev/node-jscs#master",
"babel-jscs": "^2.0.1",
```

And JSCS config:
```
jscsConfig": {
    "preset": "airbnb",
    "esprima": "./node_modules/babel-jscs",
    "fileExtensions": [
      ".js",
      ".jsx"
    ]
  },
```

**Comment by mrjoelkemp** [comment]
Try autofix for the errors :) We don't have fixing logic for everything though. 

Glad it's fixed.
