### ISSUE TITLE
jscs-babel: "unable to add an error"

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1567]
I installed the version of JSCS recommended by jscs-babel, here: https://github.com/jscs-dev/babel-jscs#install

I enabled esnext in my configuration. 

When I ran JSCS through my project, I get:

```
Warning: Unable to add an error, `line` should be a number greater than 0 but undefined given

Aborted due to warnings.
```

When I print a stack trace where it fails I get:

```
Error
    at Object.Errors._validateInput (.../node_modules/jscs/lib/errors.js:71:36)
    at Object.Errors.add (.../node_modules/jscs/lib/errors.js:46:14)
    at StringChecker._addParseError (.../node_modules/jscs/lib/string-checker.js:206:16)
    at null.<anonymous> (.../node_modules/jscs/lib/string-checker.js:98:22)
    at Array.forEach (native)
    at StringChecker.checkString (.../node_modules/jscs/lib/string-checker.js:95:31)
    at null.<anonymous> (.../node_modules/jscs/lib/checker.js:44:21)
    at Array.<anonymous> (.../node_modules/jscs/node_modules/vow/lib/vow.js:711:39)
    at Immediate.callFns [as _onImmediate] (.../node_modules/jscs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:358:17) Use --force to continue.
```

When I print out the file names that it is trying to add an error on, it prints out every file.

**Comment by stefanosala** [comment]
Same here, even without babel-jscs

**Comment by hzoo** [comment]
Should be able to close this now with babel-jscs `2.0.2` and `2.0.3`

**Comment by mrjoelkemp** [comment]
@TheSavior Mind confirming that this is resolved?

**Comment by TheSavior** [comment]
Yeah, looks good. Thanks guys

**Comment by everyonesdesign** [comment]
Seems that I got this error with jscs@2.1.1 and babel-jscs@2.0.4
