### ISSUE TITLE
Error running rule requireAlignedObjectValues

### ISSUE THREAD

**Issue by Coobaha** [jscs-dev/node-jscs#1587]
```
Error running rule requireAlignedObjectValues: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
RangeError: Invalid array length
    at TokenAssert.<anonymous> (node_modules/jscs/lib/token-assert.js:83:42)
    at TokenAssert.spacesBetween (node_modules/jscs/lib/token-assert.js:117:9)
    at node_modules/jscs/lib/rules/require-aligned-object-values.js:105:31
    at Array.forEach (native)
    at node_modules/jscs/lib/rules/require-aligned-object-values.js:104:20
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (node_modules/jscs/lib/js-file.js:478:42)
    at Object.module.exports.check (node_modules/jscs/lib/rules/require-aligned-object-values.js:63:14)
    at null.<anonymous> (node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native) at app/main/components/Modal/Modal.jsx :
     1 |import React, {PropTypes} from 'react';
--------^
     2 |import classNames from 'classnames';
     3 |import {ImmutableComponentPure} from 'common/ImmutableComponent.js';


1 code style error found.
```

if i remove dynamic object properties - check passes

```
    let podClassNames = {
      [className]      : !!className,
      [$main.pod]      : true,
      [$main.whitePod] : white,
      [$main.grouped]  : grouped,
      [$main.footer]   : footer,
      [$main.hole]     : hole
    };

```

**Comment by mrjoelkemp** [comment]
Thanks for reporting @Coobaha. So that I'm clear, you're saying the rule fails for dynamic object properties? The printed error oddly made it look like a missing `esnext: true` configuration.

**Comment by Coobaha** [comment]
@mrjoelkemp  i have `esnext : true`, and we got a  lot of files, some of them fails on imports if there dynamic object props

**Comment by mrjoelkemp** [comment]
I can't reproduce @Coobaha.

The following test passes:

```js
        it('should not report on an import plus aligned computed property names (#1587)', function() {
          checker.configure({ esnext: true });
            assert(
                checker.checkString([
                    'import React, {PropTypes} from \'react\';\n',
                    'import {ImmutableComponentPure} from \'common/ImmutableComponent.js\'',
                    'let myObject = {',
                      '[myKey]    : "myKeyValue",',
                      '[otherKey] : "myOtherValue"',
                    '};'
                ].join('\n')).isEmpty()
            );
        });
```

Any other clues?

**Comment by mrjoelkemp** [comment]
A clue! Seems like it's the MemberExpression key (e.g., `[$main.pod]`) that's causing trouble.

**Comment by Coobaha** [comment]
:+1:
