### ISSUE TITLE
requireMatchingFunctionName error with predefined variables

### ISSUE THREAD

**Issue by Famlam** [jscs-dev/node-jscs#1601]
If you have defined a variable name before, then assign it to an (anonymous) function, requireMatchingFunctionName will crash. Example code:

```javascript
var abc = function() {
  var myFunction;

  myFunction = function(name) {
    console.log('hello', name);
  };
};
```
The error message:
>Error running rule requireMatchingFunctionName: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'name' of undefined
    at checkForMember (file:///C:/Users/Famlam/Desktop/RedundancyCheck/test%20suite/jscs.js:10499:38)
    at file:///C:/Users/Famlam/Desktop/RedundancyCheck/test%20suite/jscs.js:10473:21
    at Array.forEach (native)
    at Object.3.JsFile.iterateNodesByType (file:///C:/Users/Famlam/Desktop/RedundancyCheck/test%20suite/jscs.js:1755:42)
    at Object.83.module.exports.check (file:///C:/Users/Famlam/Desktop/RedundancyCheck/test%20suite/jscs.js:10468:14)
    at Object.<anonymous> (file:///C:/Users/Famlam/Desktop/RedundancyCheck/test%20suite/jscs.js:17118:22)
    at Array.forEach (native)
    at Object.139.StringChecker._checkJsFile (file:///C:/Users/Famlam/Desktop/RedundancyCheck/test%20suite/jscs.js:17114:31)
    at Object.139.StringChecker.checkString (file:///C:/Users/Famlam/Desktop/RedundancyCheck/test%20suite/jscs.js:17059:14)
    at Object.<anonymous> (file:///C:/Users/Famlam/Desktop/RedundancyCheck/test%20suite/index.html?module=Other:5008:32) at input :

**Comment by mrjoelkemp** [comment]
Thanks for reporting @Famlam.  

@zxqfox mind looking into this? Seems like you landed some changes to that rule last.https://github.com/jscs-dev/node-jscs/commit/91e9a38c45bb41e54feccb6d004be73d54c024c4#diff-105ac0edfe6913192922933858c13d7f

**Comment by zxqfox** [comment]
Yeah, It's an old bug. I've made some fix, added some with additional tests, but not sure if it right. ;-\

**Comment by Famlam** [comment]
Thanks for the quick fix!
