### ISSUE TITLE
Problems using object spread operator with requireSpaceBeforeObjectValues

### ISSUE THREAD

**Issue by natemara** [jscs-dev/node-jscs#1624]
When trying to use object spreading while requireSpaceBeforeObjectValues is set to true, JSCS will fail to parse the entire file, dumping a large stack trace into the console. This is a minimal example that demonstrates the problem:

```js
var x = {};
var response = {y: {message: 'hello'}, ...x};
```

And the error that is generated:

```sh
$ node_modules/.bin/jscs jscsTest.js 
Error running rule requireSpaceBeforeObjectValues: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property '_tokenIndex' of undefined
    at Object.JsFile.getNextToken (/home/dcpdev/projects/clicklist_web/client/node_modules/jscs/lib/js-file.js:318:26)
    at /home/dcpdev/projects/clicklist_web/client/node_modules/jscs/lib/rules/require-space-before-object-values.js:53:37
    at Array.forEach (native)
    at /home/dcpdev/projects/clicklist_web/client/node_modules/jscs/lib/rules/require-space-before-object-values.js:43:29
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/home/dcpdev/projects/clicklist_web/client/node_modules/jscs/lib/js-file.js:478:42)
    at Object.module.exports.check (/home/dcpdev/projects/clicklist_web/client/node_modules/jscs/lib/rules/require-space-before-object-values.js:42:14)
    at null.<anonymous> (/home/dcpdev/projects/clicklist_web/client/node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/home/dcpdev/projects/clicklist_web/client/node_modules/jscs/lib/string-checker.js:161:31) at jscsTest.js :
     1 |var x = {};
--------^
     2 |var response = {y: {message: 'hello'}, ...x};
     3 |


1 code style error found.
```

If requireSpaceBeforeObjectValues is turned off in the `.jscsrc`, then the file is parsed with no problems. I am using version 2.0.0 of JSCS.

**Comment by hzoo** [comment]
I guess similar to https://github.com/jscs-dev/babel-jscs/issues/13
