### ISSUE TITLE
Exception running JSCS

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1629]
Some colored output, shouldn't be a problem
```
[1mError running rule requireDollarBeforejQueryAssignment: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'indexOf' of undefined
    at /home/testyo/repos/frontend-repo/code/node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:112:24
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/home/testyo/repos/frontend-repo/code/node_modules/jscs/lib/js-file.js:478:42)
    at Object.module.exports.check (/home/testyo/repos/frontend-repo/code/node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:72:14)
    at null.<anonymous> (/home/testyo/repos/frontend-repo/code/node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/home/testyo/repos/frontend-repo/code/node_modules/jscs/lib/string-checker.js:161:31)
    at StringChecker.checkString (/home/testyo/repos/frontend-repo/code/node_modules/jscs/lib/string-checker.js:106:14)
    at DestroyableTransform._transform (/home/testyo/repos/frontend-repo/code/node_modules/gulp-jscs/index.js:72:22)
    at DestroyableTransform.Transform._read (/home/testyo/repos/frontend-repo/code/node_modules/gulp-jscs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/home/testyo/repos/frontend-repo/code/node_modules/gulp-jscs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/home/testyo/repos/frontend-repo/code/node_modules/gulp-jscs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/home/testyo/repos/frontend-repo/code/node_modules/gulp-jscs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/home/testyo/repos/frontend-repo/code/node_modules/gulp-jscs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (/home/testyo/repos/frontend-repo/code/node_modules/gulp-jshint/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/testyo/repos/frontend-repo/code/node_modules/gulp-jshint/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)[22m at [32mmodules/adminmodus/adminVirksomhet/helsepersonell.js[39m :
 [90m    1 |[39mimport app from 'common-assets/scripts/app/app';
[90m--------^[39m
 [90m    2 |[39mimport $ from 'jquery';
 [90m    3 |[39mimport _ from 'underscore';
```

**Comment by SimenB** [comment]
The error only occurs if I have an object destructuring further down `const { hprnummer, hprrolletekst } = auth.toJSON();`

**Comment by hzoo** [comment]
Thanks for reporting! I think it's the same as https://github.com/jscs-dev/node-jscs/issues/1373

**Comment by SimenB** [comment]
Yup, probably. 3 months old...

**Comment by SimenB** [comment]
@hzoo Do I have to enable the rule again at the bottom of the file, or is such configuration on a per-file basis?

**Comment by hzoo** [comment]
Should be per file unless you just disable the rule - you should also be able to do inline comments now too if that's better in some way.

**Comment by SimenB** [comment]
I tried inline, didn't fix the exception
