### ISSUE TITLE
Error in requireMatchingFunctionName rule - Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by avishnyak** [jscs-dev/node-jscs#1643]
```
Message:
    Error running rule requireMatchingFunctionName: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'name' of undefined
  at checkForMember (gulp-jscs\node_modules\jscs\lib\rules\require-matching-function-name.js:99:38)
  at gulp-jscs\node_modules\jscs\lib\rules\require-matching-function-name.js:73:21
  at Array.forEach (native)
  at Object.JsFile.iterateNodesByType (gulp-jscs\node_modules\jscs\lib\js-file.js:478:42)
  at Object.module.exports.check (gulp-jscs\node_modules\jscs\lib\rules\require-matching-function-name.js:68:14)
  at [object Object].<anonymous> (gulp-jscs\node_modules\jscs\lib\string-checker.js:165:22)
  at Array.forEach (native)
  at [object Object].StringChecker._checkJsFile (gulp-jscs\node_modules\jscs\lib\string-checker.js:161:31)
  at [object Object].StringChecker.checkString (gulp-jscs\node_modules\jscs\lib\string-checker.js:106:14)
  at DestroyableTransform._transform (gulp-jscs\index.js:72:22)
  at DestroyableTransform.Transform._read (gulp-jscs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:10)
  at DestroyableTransform.Transform._write (gulp-jscs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:160:12)
  at doWrite (gulp-jscs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:326:12)
  at writeOrBuffer (gulp-jscs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:312:5)
  at DestroyableTransform.Writable.write (gulp-jscs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:239:11)
  at write (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
  at flow (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:104:17)
  at emitReadable_ (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
  at emitReadable (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
  at readableAddChunk (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
  at afterTransform (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:101:12)
  at TransformState.afterTransform (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (gulp\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
  at DestroyableTransform.Transform._read (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
  at doWrite (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
  at writeOrBuffer (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
  at write (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
  at flow (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:104:17)
  at emitReadable_ (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
  at emitReadable (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
  at readableAddChunk (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
  at afterTransform (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:101:12)
  at TransformState.afterTransform (gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
  at gulp\node_modules\vinyl-fs\lib\src\getContents\bufferFile.js:12:5
  at evalmachine.<anonymous>:334:14
  at gulp\node_modules\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:102:5
  at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
 at angular-polyfill.js :
     1 |function minErr(module) {
--------^
     2 |    return function () {
     3 |        var code         = arguments[0],
```

And here is the source of the function it is having problems with:
```javascript
function minErr(module) {
    return function () {
        var code         = arguments[0],
            prefix       = '[' + (module ? module + ':' : '') + code + '] ',
            template     = arguments[1],
            templateArgs = arguments,
            message, i;

        function stringify(obj) {
            if (typeof obj === 'function') {
                return obj.toString().replace(/ \{[\s\S]*$/, '');
            } else if (typeof obj === 'undefined') {
                return 'undefined';
            } else if (typeof obj !== 'string') {
                return JSON.stringify(obj);
            }

            return obj;
        }

        message = prefix + template.replace(/\{\d+\}/g, function (match) {
                var index = +match.slice(1, -1), arg;

                if (index + 2 < templateArgs.length) {
                    arg = templateArgs[index + 2];

                    return stringify(arg);
                }

                return match;
            });

        message = message + '\nhttp://errors.angularjs.org/"NG_VERSION_FULL"/' + (module ? module + '/' : '') + code;

        for (i = 2; i < arguments.length; i++) {
            message = message + (i == 2 ? '?' : '&') + 'p' + (i - 2) + '=' + encodeURIComponent(stringify(arguments[i]));
        }

        return new Error(message);
    };
}
```

**Comment by hzoo** [comment]
Looks like this is the same as https://github.com/jscs-dev/node-jscs/issues/1601?

**Comment by avishnyak** [comment]
I don't think so.  After some testing, it seems to have a problem with the first character of the file no matter what is there.

I added a blank line and still got the same error & stack trace.

```
 at angular-polyfill.js :
     1 |
--------^
     2 |function minErr(module) {
     3 |    return function () {
```

I have tried changing encoding of the file in WebStorm and that seems to not have any effect.  I wonder if the error is somewhere else in the file but the pointer does not show where the error actually is?

**Comment by hzoo** [comment]
Can you try testing on the master branch (since that fix doesn't have a release yet) to see if that fixes it?

If there's still an issue, if you can reduce the code snippet that would be helpful!

**Comment by avishnyak** [comment]
Unfortunately, I'm under a tight deadline so I can't do that right now but I was able to narrow down the error to the following code:

```javascript
            function instantiate(Type, locals) {
                var Constructor, instance, returnedValue;

                // jscs:disable requireFunctionDeclarations
                Constructor = function () {};
                // jscs:enable requireFunctionDeclarations

                // Check if Type is annotated and use just the given function at n-1 as parameter
                // e.g. someModule.factory('greeter', ['$window', function(renamed$window) {}]);
                Constructor.prototype = (_.isArray(Type) ? Type[Type.length - 1] : Type).prototype;
                instance = new Constructor();
                returnedValue = invoke(Type, instance, locals);

                return _.isObject(returnedValue) || _.isFunction(returnedValue) ? returnedValue : instance;
            }
```

There is still a bug in that JSCS does not get the line number correct when reporting the error, but for now I'll just turn off that rule using comments.

**Comment by hzoo** [comment]
@avishnyak Ok I can reproduce with 2.0.0 but cannot in master so it looks like it's fixed to me. When you get a chance try it on master or wait for the next release (next week maybe?). I'm going to close for now, if not feel free to reopen.
