### ISSUE TITLE
Weird JSCS error

### ISSUE THREAD

**Issue by michahell** [jscs-dev/node-jscs#1690]
I'm getting the following JSCS error, using WebStorm 10 (don't ask), JSCS npm module version jscs@2.1.0 on OSX 10.10.3. I have no further JSCS errors in the file i'm editing, which contains Yuidoc doc strings like so:

```
/**
 * @class  someClassname3
 * @namespace prefix
 * @extends prefix.someClassname3
 */
```

```
TypeError: Cannot read property 'loc' of undefined
    at /usr/local/lib/node_modules/jscs/lib/rules/validate-indentation.js:479:58
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/usr/local/lib/node_modules/jscs/lib/js-file.js:478:42)
    at generateIndentations (/usr/local/lib/node_modules/jscs/lib/rules/validate-indentation.js:471:18)
    at Object.module.exports.check (/usr/local/lib/node_modules/jscs/lib/rules/validate-indentation.js:576:9)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/usr/local/lib/node_modules/jscs/lib/string-checker.js:161:31)
    at StringChecker.checkString (/usr/local/lib/node_modules/jscs/lib/string-checker.js:106:14)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/checker.js:44:21) at KaartBasisView3.js :
     1 |/**
--------^
     2 | * @class  KaartBasisView3
     3 | * @namespace vgm


1 code style error found.
```

**Comment by hzoo** [comment]
Not able to reproduce with only the comment - can you post the smallest reproducible code snippet? I see it's an error with `validateIndentation`, and are you using `esnext`?

**Comment by michahell** [comment]
Hmm, understood. I'm not sure what is causing this, let me try and find a MWE!

**Comment by michahell** [comment]
Solved! It was caused by an empty ```switch {}``` statement.

MWE:

```
/**
 * @class  SomeClass3
 * @namespace prefix
 * @extends prefix.SomeClass3
 */
prefix.SomeClass3 = prefix.SomeOtherClass3.extend({

  /**
   * Description
   * @method construct
   * @param {} args
   * @return
   */
  construct: function(args) {
    // bla
  },

  /**
   * Description
   * @method handleEvent
   * @param {} event
   * @param {} sender
   * @param {} args
   * @return
   */
  handleEvent: function(event) {
    if (true) {
      switch (event) {

      }
    }
  }

});
```

Comment and uncomment the switch statement to get the error. JSCS in webstorm 10 DOES give another error if disallow Empty blocks is set to true, but IMO this should not happen still?

**Comment by hzoo** [comment]
I guess the other error is overriding the `disallowEmptyBlocks` one. But yeah that is an issue - and actually searching it's the same as https://github.com/jscs-dev/node-jscs/issues/1528. Thanks for reporting!
