### ISSUE TITLE
Error: Cannot find module 'lodash/lang/isFunction'

### ISSUE THREAD

**Issue by oliversalzburg** [jscs-dev/node-jscs#1730]
I just installed JSCS into a project of mine. When I try to run it, I get the following error:
```
$ node_modules/jscs/bin/jscs
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash/lang/isFunction'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (d:\fm-log\node_modules\jscs\node_modules\babel-core\lib\api\node.js:21:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by oliversalzburg** [comment]
Re-installing the package fixed it.

**Comment by mrjoelkemp** [comment]
Thanks for reporting. To be clear, you reinstalled jscs and it worked
right? You didn't install lodash separately to make it work.

**Comment by oliversalzburg** [comment]
@mrjoelkemp Correct. I realized that the installed `lodash` dependency was missing a lot of files. Something must have went wrong during the initial installation of `jscs`. I cleared out my whole `node_modules` and ran `npm i` again.

**Comment by mrjoelkemp** [comment]
Awesome. Thanks for the clarification! Enjoy.

**Comment by simkessy** [comment]
I'm getting this issue after trying to update to 4.6.1. Not sure how to fix it

**Comment by mrjoelkemp** [comment]
Try npm cache clear, removing your node_modules folder (or just jscs) and
then doing an npm install.

Does that work?
