### ISSUE TITLE
Error with `disallowParenthesesAroundArrowParam`

### ISSUE THREAD

**Issue by jmeas** [jscs-dev/node-jscs#1754]
I updated an application to use `gulp-jscs@2.0.0`, then set `"disallowParenthesesAroundArrowParam"` to be true. Running the task causes numerous files in the application to break, though not all. It's likely that it's just the files that use arrow functions.

One stack trace is:

```js
Error running rule disallowParenthesesAroundArrowParam: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'type' of undefined
    at /Users/jmeas/path/to/my_project/node_modules/gulp-jscs/node_modules/jscs/lib/rules/disallow-parentheses-around-arrow-param.js:62:59
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/jmeas/path/to/my_project/node_modules/gulp-jscs/node_modules/jscs/lib/js-file.js:488:42)
    at Object.module.exports.check (/Users/jmeas/path/to/my_project/node_modules/gulp-jscs/node_modules/jscs/lib/rules/disallow-parentheses-around-arrow-param.js:57:14)
    at null.<anonymous> (/Users/jmeas/path/to/my_project/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/jmeas/path/to/my_project/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:161:31)
    at StringChecker.checkString (/Users/jmeas/path/to/my_project/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:106:14)
    at DestroyableTransform._transform (/Users/jmeas/path/to/my_project/node_modules/gulp-jscs/index.js:72:22)
    at DestroyableTransform.Transform._read (/Users/jmeas/path/to/my_project/node_modules/gulp-jscs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10) at pods/schedule-chart/views/chart-view/index.js :
     1 |import $ from 'jquery';
--------^
     2 |import _ from 'underscore';
     3 |import moment from 'moment';
``` 

All of the errors happen at line1, no matter what it is (even if it's, say, a comment).

**Comment by hzoo** [comment]
Thanks for the report - I just fixed this in master. Same as https://github.com/jscs-dev/node-jscs/issues/1747

**Comment by jmeas** [comment]
Thanks @hzoo! Sorry for the duplicate issue – I ran some searches and didn't find the original issue.

**Comment by Awk34** [comment]
I'm having this issue also. I look forward to the next version bump! Thanks @hzoo :)
