### ISSUE TITLE
SyntaxError: Unable to load JSCS config file

### ISSUE THREAD

**Issue by RehanSaeed** [jscs-dev/node-jscs#1786]
I am using Gulp 3.9.0 and Gulp-jscs 2.0.0. When I try to runt he following Gulp task I get the error below:

```
gulp.task("lint-js", function () {
    return gulp
        .src(paths.scripts + "**/*.js")
        .pipe(jscs());
});
```

```
> cmd.exe /c gulp -b "C:\WebApplication1\WebApplication1" --color --gulpfile "C:\WebApplication1\WebApplication1\Gulpfile.js" lint-js
[18:53:55] Using gulpfile C:\WebApplication1\WebApplication1\Gulpfile.js
[18:53:55] Starting 'lint-js'...
[18:53:55] 'lint-js' errored after 234 ms
[18:53:55] SyntaxError: Unable to load JSCS config file at C:\WebApplication1\WebApplication1\.jscsrc
Unexpected token ﻿
    at Object.parse (native)
    at Object.exports.getContent (C:\WebApplication1\WebApplication1\node_modules\gulp-jscs\node_modules\jscs\lib\cli-config.js:74:28)
    at Object.exports.load (C:\WebApplication1\WebApplication1\node_modules\gulp-jscs\node_modules\jscs\lib\cli-config.js:112:21)
    at module.exports (C:\WebApplication1\WebApplication1\node_modules\gulp-jscs\index.js:37:37)
    at Gulp.gulp.task.sources.css.map.gulp.src.pipe.pipe.pipe.pipe.pipe.pipe.minifyCss.keepSpecialComments (C:\WebApplication1\WebApplication1\Gulpfile.js:232:15)
    at module.exports (C:\WebApplication1\WebApplication1\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\WebApplication1\WebApplication1\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\WebApplication1\WebApplication1\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\WebApplication1\WebApplication1\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\WebApplication1\WebApplication1\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
Process terminated with code 1.
```

Here is a full copy of my .jscsrc file:

```
{
  "requireCurlyBraces": [
    "if",
    "else",
    "for",
    "while",
    "do",
    "try",
    "catch"
  ],
  "requireSpaceAfterKeywords": [
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "return",
    "try",
    "catch",
    "function",
    "typeof"
  ],
  "requireSpaceBeforeBlockStatements": true,
  "requireParenthesesAroundIIFE": true,
  "requireSpacesInConditionalExpression": true,
  "disallowSpacesInNamedFunctionExpression": {
    "beforeOpeningRoundBrace": true
  },
  "disallowSpacesInFunctionDeclaration": {
    "beforeOpeningRoundBrace": true
  },
  "requireSpaceBetweenArguments": true,
  "requireMultipleVarDecl": "onevar",
  "requireVarDeclFirst": true,
  "requireBlocksOnNewline": true,
  "disallowEmptyBlocks": true,
  "disallowSpacesInsideArrayBrackets": true,
  "disallowSpacesInsideParentheses": true,
  "disallowDanglingUnderscores": true,
  "requireCommaBeforeLineBreak": true,
  "disallowSpaceAfterPrefixUnaryOperators": true,
  "disallowSpaceBeforePostfixUnaryOperators": true,
  "disallowSpaceBeforeBinaryOperators": [
    ","
  ],
  "requireSpacesInForStatement": true,
  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true,
    "beforeOpeningCurlyBrace": true
  },
  "requireSpaceBeforeBinaryOperators": true,
  "requireSpaceAfterBinaryOperators": true,
  "disallowKeywords": [
    "with",
    "continue"
  ],
  "validateIndentation": 4,
  "disallowMixedSpacesAndTabs": true,
  "disallowTrailingWhitespace": true,
  "disallowTrailingComma": true,
  "disallowKeywordsOnNewLine": [
    "else"
  ],
  "requireLineFeedAtFileEnd": true,
  "requireCapitalizedConstructors": true,
  "requireDotNotation": true,
  "disallowNewlineBeforeBlockStatements": true,
  "disallowMultipleLineStrings": true,
  "requireSpaceBeforeObjectValues": true
}
```

**Comment by hzoo** [comment]
The `.jscsrc` file itself looks fine - maybe your path to the `.jscsrc` is wrong

**Comment by RehanSaeed** [comment]
According to the error, its looking for the file in the correct location.

**Comment by markelog** [comment]
Sounds like an issue with gulp task, `.jscsrc` is correct

**Comment by tbandixen** [comment]
Changing the encoding of the `.jscsrc` file to "UTF-8 without BOM" solved it for me.

**Comment by RehanSaeed** [comment]
@tbandixen Thanks, I've been stuck on this for a couple of days. For others with this problem using Windows and Visual Studio, you need to save the file as 'UTF8 without Signature' which is the same thing as BOM or Byte Order Mark.

Ideally gulp-jscm or jscm itself should handle either encoding.
