### ISSUE TITLE
Error running rule disallowParenthesisAroundArrowParam

### ISSUE THREAD

**Issue by CrshOverride** [jscs-dev/node-jscs#1802]
The stack trace is below (this is the only instance of this issue in my entire Ember CLI app):

```
TypeError: Cannot read property 'type' of undefined
  at /samba/ember-workspace/csa/node_modules/broccoli-jscs/node_modules/jscs/lib/rules/disallow-parentheses-around-arrow-param.js:62:59
  at Array.forEach (native)
  at Object.JsFile.iterateNodesByType (/samba/ember-workspace/csa/node_modules/broccoli-jscs/node_modules/jscs/lib/js-file.js:488:42)
  at Object.module.exports.check (/samba/ember-workspace/csa/node_modules/broccoli-jscs/node_modules/jscs/lib/rules/disallow-parentheses-around-arrow-param.js:57:14)
  at null.<anonymous> (/samba/ember-workspace/csa/node_modules/broccoli-jscs/node_modules/jscs/lib/string-checker.js:165:22)
  at Array.forEach (native)
  at StringChecker._checkJsFile (/samba/ember-workspace/csa/node_modules/broccoli-jscs/node_modules/jscs/lib/string-checker.js:161:31)
  at StringChecker.checkString (/samba/ember-workspace/csa/node_modules/broccoli-jscs/node_modules/jscs/lib/string-checker.js:106:14)
  at JSCSFilter.processString (/samba/ember-workspace/csa/node_modules/broccoli-jscs/index.js:72:31)
  at /samba/ember-workspace/csa/node_modules/broccoli-jscs/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:33:42 at pods/account/controller.js :
  1 |import Ember from 'ember';
```

**Comment by hzoo** [comment]
Thanks for the report @CrshOverride! This is the same as https://github.com/jscs-dev/node-jscs/issues/1754. I have a fix in master.

Sorry we haven't released yet, should be soon.
