### ISSUE TITLE
Cannot read property 'type' of undefined in disallowQuotedKeysInObjects

### ISSUE THREAD

**Issue by vizath** [jscs-dev/node-jscs#1808]
Hello,
I do not know if you still support esprima-fb (said deprecated here https://github.com/jscs-dev/node-jscs/issues/1573#issuecomment-125937674), but I have this error with it:
```
Error running rule disallowQuotedKeysInObjects: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'type' of undefined
    at c:\app\node_modules\jscs\lib\rules\disallow-quoted-keys-in-objects.js:71:24
    at Array.forEach (native)
    at c:\app\node_modules\jscs\lib\rules\disallow-quoted-keys-in-objects.js:68:29
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (c:\app\node_modules\jscs\lib\js-file.js:488:42)
    at Object.module.exports.check (c:\app\node_modules\jscs\lib\rules\disallow-quoted-keys-in-objects.js:67:14)
    at null.<anonymous> (c:\app\node_modules\jscs\lib\string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (c:\app\node_modules\jscs\lib\string-checker.js:161:31)
    at StringChecker.checkString (c:\app\node_modules\jscs\lib\string-checker.js:106:14) at test.js
     1 |hello({ ...this.props });
--------^
```

Using `esnext:true` instead of exprima fixes this issue, but #1804 is still pending.

jscs version 2.1.1

**Comment by hzoo** [comment]
Yeah the esprima-fb parser itself is deprecated. FB isn't maintaining it anymore and are using babel (which `esnext` uses).

**Comment by hzoo** [comment]
Going to close this - will have to figure out #1804
