### ISSUE TITLE
isEmpty of null

### ISSUE THREAD

**Issue by danielstjules** [jscs-dev/node-jscs#1816]
With 2.2.0, I'm getting:
```
TypeError: Cannot read property 'isEmpty' of null
    at /Users/dstjules/git/project/node_modules/jscs/lib/reporters/console.js:10:20
    at Array.forEach (native)
    at Object.module.exports [as writer] (/Users/dstjules/git/project/node_modules/jscs/lib/reporters/console.js:9:22)
    at /Users/dstjules/git/project/node_modules/jscs/lib/cli.js:151:18
    at Array.<anonymous> (/Users/dstjules/git/project/node_modules/jscs/node_modules/vow/lib/vow.js:711:56)
    at Immediate.callFns [as _onImmediate] (/Users/dstjules/git/project/node_modules/jscs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:357:17)
```

However, fixing that reveals another issue:
```
TypeError: Cannot read property 'isEmpty' of null
    at /Users/dstjules/git/project/node_modules/jscs/lib/cli.js:155:24
```

Can't right now, but hopefully I can come up with a small example later tonight.

**Comment by hzoo** [comment]
Thanks for the report - yeah please add a snippet to reproduce and your config. If you run with `--verbose` then we can see what rule is erroring

**Comment by danielstjules** [comment]
Config I'm using:
``` javascript
{
  "disallowEmptyBlocks": true,
  "disallowMixedSpacesAndTabs": true,
  "disallowSpaceBeforeComma": true,
  "disallowSpaceBeforeSemicolon": true,
  "disallowTrailingWhitespace": true,
  "disallowTrailingComma": true,
  "disallowSpacesInsideParentheses": true,
  "requireCapitalizedConstructors": true,
  "requireLineFeedAtFileEnd": true,
  "requireSemicolons": true,
  "requireSpaceBetweenArguments": true,
  "disallowYodaConditions": [
    "==",
    "===",
    "!=",
    "!=="
  ],
  "requireSpaceAfterKeywords": [
    "do",
    "for",
    "if",
    "else",
    "switch",
    "case",
    "try",
    "catch",
    "void",
    "while",
    "with",
    "return",
    "typeof"
  ],
  "excludeFiles": [
    "node_modules/**",
    "public/assets/src/js/p-music-wall.js"
  ]
}
```

Unfortunately, `--verbose` doesn't seem to reveal much:

```
> jscs --verbose test public/assets/src/js/p-* lib scripts

TypeError: Cannot read property 'isEmpty' of null
    at /Users/dstjules/git/project/node_modules/jscs/lib/reporters/console.js:10:20
    at Array.forEach (native)
    at Object.module.exports [as writer] (/Users/dstjules/git/project/node_modules/jscs/lib/reporters/console.js:9:22)
    at /Users/dstjules/git/project/node_modules/jscs/lib/cli.js:151:18
    at Array.<anonymous> (/Users/dstjules/git/project/node_modules/jscs/node_modules/vow/lib/vow.js:711:56)
    at Immediate.callFns [as _onImmediate] (/Users/dstjules/git/project/node_modules/jscs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:357:17)
```

**Comment by markelog** [comment]
Hm, i think i know what the issue is, we would need to release again though

**Comment by hzoo** [comment]
Ok shouldn't of closed that - @danielstjules can you check if that PR/commit fixes it?

**Comment by hzoo** [comment]
2.2.1 is released! Hopefully fixes it?

**Comment by danielstjules** [comment]
That fixed it, thank you! :)
