### ISSUE TITLE
"disallowCommaBeforeLineBreak": { "allExcept": [ "function" ] } does not work

### ISSUE THREAD

**Issue by tellnes** [jscs-dev/node-jscs#1841]
jscs -V
2.2.1

```
disallowCommaBeforeLineBreak: Error running rule disallowCommaBeforeLineBreak: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'some' of undefined
    at canSkip (/usr/local/lib/node_modules/jscs/lib/rules/disallow-comma-before-line-break.js:90:53)
    at /usr/local/lib/node_modules/jscs/lib/rules/disallow-comma-before-line-break.js:96:17
    at /usr/local/lib/node_modules/jscs/lib/js-file.js:603:17
    at Array.forEach (native)
    at Object.JsFile.iterateTokensByTypeAndValue (/usr/local/lib/node_modules/jscs/lib/js-file.js:601:26)
    at Object.module.exports.check (/usr/local/lib/node_modules/jscs/lib/rules/disallow-comma-before-line-break.js:95:14)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/usr/local/lib/node_modules/jscs/lib/string-checker.js:161:31)
    at StringChecker.checkString (/usr/local/lib/node_modules/jscs/lib/string-checker.js:106:14) at rules/browserify._js :
```

I belive https://github.com/jscs-dev/node-jscs/commit/cd8ce2e36b4c7fece12ad33cc7e7709ff71fd561 is responsible.

**Comment by hzoo** [comment]
If it is then it might be the same as https://github.com/jscs-dev/node-jscs/issues/1746? @dreef3 

Can you post a code snippet that would result in the error? Thanks for the report!

**Comment by hzoo** [comment]
Ok we're going to release 2.3.0 soon
