### ISSUE TITLE
False positive: requireDollarBeforejQueryAssignment and array destructuring

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1860]
Just like #1373, but for array destructuring.

I'm done with this buggy rule, but thought I could at least try to fix it :laughing:

**Comment by artptr** [comment]
There is an error when this code is analyzed:
```
export function foo() {
	let a, b;
	[a, b] = [1, 2];
}
```
It says:
```
TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (.../node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:130:53)
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (.../node_modules/jscs/lib/js-file.js:545:42)
    at Object.module.exports.check (.../node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:72:14)
    at null.<anonymous> (.../node_modules/jscs/lib/string-checker.js:165:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (.../node_modules/jscs/lib/string-checker.js:161:31)
    at StringChecker.checkString (.../node_modules/jscs/lib/string-checker.js:106:14)
    at null.<anonymous> (.../node_modules/jscs/lib/checker.js:45:21)
    at Array.<anonymous> (.../node_modules/jscs/node_modules/vow/lib/vow.js:711:39) at test.js :
     1 |export function foo() {
--------^
     2 | let a, b;
     3 | [a, b] = [1, 2];
```
