### ISSUE TITLE
new rule "requireSpacesInGenerator" not working as expected

### ISSUE THREAD

**Issue by AuthorProxy** [jscs-dev/node-jscs#1955]
Using sublime node-jscs 2.5.0

```
function* populateWithEmptyZones( usedTimezones) {
    let zoneHours = [...new Array(24)].map((x, y) => y - 11);

    for (let i of zoneHours) {
      let usedTimezone =
        usedTimezones.find(entry => entry.utcshift === i) ||
        Object.assign({ utcshift: i }, defaultZone);

      usedTimezone.utcshift = usedTimezone.utcshift > 0 ? `+${usedTimezone.utcshift}` : usedTimezone.utcshift;
      yield usedTimezone;
    }
  }
```

Getting this in console:

```
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3">
    <file name="c:\users\a5aa5~1.kos\appdata\local\temp\SublimeLinter3-a.kostukov\details.js">
        <error line="1" column="1" severity="error" message="internalError: Error running rule disallowUnusedParams: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
RangeError: Maximum call stack size exceeded
    at keys (native)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:78:24)
    at Referencer.Visitor.visit (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:93:26)
    at Referencer.Visitor.visit (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:93:26)
    at Referencer.Visitor.visit (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:93:26)
    at Referencer.Visitor.visit (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:93:26)" source="jscs" />
        <error line="25" column="36" severity="error" message="disallowSpacesInsideParentheses: Illegal space after opening round bracket" source="jscs" />
    </file>
</checkstyle> 
```

then after I use jscs autoformatter, it removes a space after first parenth (before usedTimezones param):
```
function* populateWithEmptyZones(usedTimezones) {
```

and notify me about new error:
```
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3">
    <file name="c:\users\a5aa5~1.kos\appdata\local\temp\SublimeLinter3-a.kostukov\details.js">
        <error line="1" column="1" severity="error" message="internalError: Error running rule disallowUnusedParams: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
RangeError: Maximum call stack size exceeded
    at keys (native)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:78:24)
    at Referencer.Visitor.visit (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:93:26)
    at Referencer.Visitor.visit (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:93:26)
    at Referencer.Visitor.visit (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:93:26)
    at Referencer.Visitor.visit (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (C:\Users\a.kostukov\AppData\Roaming\npm\node_modules\jscs\node_modules\escope\node_modules\esrecurse\esrecurse.js:93:26)" source="jscs" />
        <error line="25" column="36" severity="error" message="requireSpacesInGenerator: Missing space after star" source="jscs" />
    </file>
</checkstyle> 
```

And if I again use autoformatter it put a space back as before:
```
function* populateWithEmptyZones( usedTimezones) {
```

and so on..

My config params:
```
"disallowSpacesInsideParentheses": true,
"requireSpaceBetweenArguments": true,
"requireSpacesInGenerator": {
    "afterStar": true
}
```

**Comment by hzoo** [comment]
Well that's weird since it's saying `Error running rule disallowUnusedParams` even though it's not in your config?

**Comment by AuthorProxy** [comment]
@hzoo I also have
```
"disallowUnusedParams": true
```

just think that it's not the case of wrong linting, if you need I can attach all other 200 line config options here

**Comment by hzoo** [comment]
No I have the PR for requireSpacesInGenerator since it's a bug - see if that works for you.
