### ISSUE TITLE
Error running jscs

### ISSUE THREAD

**Issue by danny-andrews** [jscs-dev/node-jscs#1999]
```
RangeError: Maximum call stack size exceeded
    at Referencer.Visitor.visitChildren (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js)
    at Referencer.Visitor.visit (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.MemberExpression (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/lib/referencer.js:420:22)
    at Referencer.Visitor.visit (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.MemberExpression (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/lib/referencer.js:420:22)
    at Referencer.Visitor.visit (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.MemberExpression (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/lib/referencer.js:420:22) at src/serializers/camel-case-serializer.js :
     1 |import humps from 'humps';
--------^
     2 |import JsonSerializer from './json-serializer';
     3 |
```

**Comment by danny-andrews** [comment]
Dupe of #2002.
