### ISSUE TITLE
Error running jscs

### ISSUE THREAD

**Issue by danny-andrews** [jscs-dev/node-jscs#2000]
```
Error running rule disallowUnusedParams: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
RangeError: Maximum call stack size exceeded
    at Function.isArray (native)
    at Referencer.Visitor.visitChildren (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:84:27)
    at Referencer.CallExpression (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/lib/referencer.js:480:22)
    at Referencer.Visitor.visit (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.CallExpression (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/lib/referencer.js:480:22)
    at Referencer.Visitor.visit (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/Users/dannya/Projects/Work/sw-purchasing/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26) at src/serializers/json-serializer.js :
     1 |import Serializer from './serializer';
--------^
     2 |
     3 |export default class extends Serializer {
```

**Comment by danny-andrews** [comment]
Dupe of #2002.
