### ISSUE TITLE
Jscs chokes on es6 classes with constructor which calls super with "disallowUnusedParams" option set to true

### ISSUE THREAD

**Issue by danny-andrews** [jscs-dev/node-jscs#2002]
Every time I run jscs against a file which has an es6 with a constructor that calls super, it chokes.
.jscsrc:
```json
{
  "disallowUnusedParams": true
}
```
src/example.js:
```js
import Parent from './parent';

export default class extends Parent {
  constructor() {
    super('hi parent');
  }
}
```
Example error message
```
Error running rule disallowUnusedParams: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
RangeError: Maximum call stack size exceeded
    at Function.isArray (native)
    at Referencer.Visitor.visitChildren (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:84:27)
    at Referencer.CallExpression (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/lib/referencer.js:480:22)
    at Referencer.Visitor.visit (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.Visitor.visit (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:112:14)
    at Referencer.Visitor.visitChildren (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26)
    at Referencer.CallExpression (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/lib/referencer.js:480:22)
    at Referencer.Visitor.visit (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (example_project/node_modules/grunt-jscs/node_modules/jscs/node_modules/escope/node_modules/esrecurse/esrecurse.js:93:26) at src/example.js :
     1 |import Parent from './parent';
--------^
     2 |
     3 |export default class extends Parent {
```
Note, if I comment out the call to super in the constructor, everything works as expected.

**Comment by markelog** [comment]
Yeah, all because of the `escope` which can't work with babel AST :/

**Comment by danny-andrews** [comment]
Ah, bummer. So this is a known issue then?

**Comment by markelog** [comment]
Yeah, bunch of issues with inability of `escope` to work with circular structures :/

**Comment by hzoo** [comment]
I think its related to multiple version of escope/estraverse (the same issue in eslint/babel-eslint). https://github.com/babel/babel-eslint/pull/209, https://github.com/eslint/eslint/issues/4485, some others? I haven't updated babel-jscs at all so need to port over babel-eslint changes

**Comment by markelog** [comment]
Basically, if parser generates AST with circular refs `escope` will go down, but the sad part is, no one of the maintainers of that package is interesting on fixing it :/

**Comment by gibson042** [comment]
> parser generates AST with circular refs

* [**abstract syntax tree** (**AST**)](https://en.wikipedia.org/wiki/Abstract_syntax_tree): "a tree representation of the abstract syntactic structure of source code"
* [**tree**](https://en.wikipedia.org/wiki/Directed_tree): "an undirected graph in which any two vertices are connected by _exactly_ one path. In other words, any connected graph without simple cycles is a tree."

https://github.com/estree/estree is cycle-free for good reason.

**Comment by hzoo** [comment]
There are underscored properties like `_paths` which could do that (info on scopes, parent/child, etc)

**Comment by markelog** [comment]
@gibson042 sure, but we don't parse ourselves
@hzoo underscore is meaningless :/

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
