### ISSUE TITLE
TypeError Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by megahertz** [jscs-dev/node-jscs#2042]
This exception raises on the following code:
```js
var Class = function() {};
/**
 * @return {Class}
 */
Class.create = function() {
    return new this();
};
```

Stack:
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at jsDocMatchType (/www/mg-model/node_modules/jscs-jsdoc/lib/jsdoc.js:544:24)
    at DocType.match (/www/mg-model/node_modules/jscs-jsdoc/lib/jsdoc.js:171:16)
    at /www/mg-model/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc/check-return-types.js:23:23
    at Array.forEach (native)
    at Object.checkReturnTypes (/www/mg-model/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc/check-return-types.js:22:31)
    at /www/mg-model/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:145:27
    at Array.forEach (native)
    at DocComment.<anonymous> (/www/mg-model/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:144:46)
    at Array.forEach (native)
    at DocComment.forEachTag [as iterate] (/www/mg-model/node_modules/jscs-jsdoc/lib/jsdoc.js:86:19)
```

**Comment by zxqfox** [comment]
Thanks for report!

**Comment by davidrapin** [comment]
Same error here:

```
Error running rule jsDoc: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'toLowerCase' of undefined
    at jsDocMatchType (/Users/david/Code/linkurious-server/node_modules/grunt-jscs/node_modules/jscs/node_modules/jscs-jsdoc/lib/jsdoc.js:544:24)
    at DocType.match (/Users/david/Code/linkurious-server/node_modules/grunt-jscs/node_modules/jscs/node_modules/jscs-jsdoc/lib/jsdoc.js:171:16)
    at /Users/david/Code/linkurious-server/node_modules/grunt-jscs/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc/check-return-types.js:23:23
    at Array.forEach (native)
    at Object.checkReturnTypes (/Users/david/Code/linkurious-server/node_modules/grunt-jscs/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc/check-return-types.js:22:31)
    at /Users/david/Code/linkurious-server/node_modules/grunt-jscs/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:145:27
    at Array.forEach (native)
    at DocComment.<anonymous> (/Users/david/Code/linkurious-server/node_modules/grunt-jscs/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:144:46)
    at Array.forEach (native)
    at DocComment.forEachTag [as iterate] (/Users/david/Code/linkurious-server/node_modules/grunt-jscs/node_modules/jscs/node_modules/jscs-jsdoc/lib/jsdoc.js:86:19) at ./test/data/graph/GraphSetup.js :
     1 |/**
--------^
     2 | * LINKURIOUS CONFIDENTIAL
     3 | * Copyright Linkurious SAS 2012 - 2015
>> 1 code style errors found!
Warning: Task "jscs:src" failed. Use --force to continue.
```

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
