### ISSUE TITLE
Unable to add an error, `column` should be a positive number but -1 given

### ISSUE THREAD

**Issue by jkryl** [jscs-dev/node-jscs#2066]
This is how I run jscs and I get this error which was reported already before and is said to be fixed. I'm using the latest version 2.8.0. It happens only with a particular source file and not with others.
```
/repos/nef/nef-core/node_modules/jscs/bin/jscs -c /repos/nef/nef-core/etc/jscs.json --max-errors=-1 -r /repos/nef/nef-core/lib/jscs/jscs-reporter.js nef-core/workers/rest/restServer.js
Error running rule jsDoc: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
AssertionError: Unable to add an error, `column` should be a positive number but -1 given
    at Object.Errors._validateInput (/repos/nef/nef-core/node_modules/jscs/lib/errors.js:73:9)
    at Object.Errors.add (/repos/nef/nef-core/node_modules/jscs/lib/errors.js:46:14)
    at addError (/repos/nef/nef-core/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:166:28)
    at /repos/nef/nef-core/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:181:25
    at Object.requireReturnTypes (/repos/nef/nef-core/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc/require-return-types.js:17:9)
    at /repos/nef/nef-core/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:145:27
    at Array.forEach (native)
    at DocComment.<anonymous> (/repos/nef/nef-core/node_modules/jscs/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:144:46)
    at Array.forEach (native)
    at DocComment.forEachTag [as iterate] (/repos/nef/nef-core/node_modules/jscs/node_modules/jscs-jsdoc/lib/jsdoc.js:86:19) at nef-core/workers/rest/restServer.js :
     1 |/**
--------^
     2 | * @fileOverview Generic REST server implementation.
     3 | *

1 code style error(s) in nef-core/workers/rest/restServer.js
Total error count: 1
```

style configuration file looks as follows:
```
{
    "preset": "google",
    "validateIndentation": 4
}
```

**Comment by markelog** [comment]
Yeah, jsdoc plugin requires some love

**Comment by zxqfox** [comment]
Guess this doc block incorrectly bound to the followed `module.exports = function`.

Would be nice to have some minimal code after this jsdoc block to repeat. Please?

**Comment by Prairie-Falcon** [comment]
I ran into this one, too.

    internalError: Error running rule jsDoc: This is an issue with JSCS and not your codebase.
    Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
AssertionError: Unable to add an error, `column` should be a positive number but -1 given
    at Object.Errors._validateInput (C:\Users\frVVLsPK\AppData\Roaming\npm\node_modules\jscs\lib\errors.js:73:9)
    at Object.Errors.add (C:\Users\frVVLsPK\AppData\Roaming\npm\node_modules\jscs\lib\errors.js:46:14)
    at addError (C:\Users\frVVLsPK\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:166:28)
    at C:\Users\frVVLsPK\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:181:25
    at Object.requireReturnTypes (C:\Users\frVVLsPK\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc\require-return-types.js:17:9)
    at C:\Users\frVVLsPK\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:145:27
    at Array.forEach (native)
    at DocComment.<anonymous> (C:\Users\frVVLsPK\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:144:46)
    at Array.forEach (native)
    at DocComment.forEachTag [as iterate] (C:\Users\frVVLsPK\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\jsdoc.js:86:19) at utilModule.js :
     1 |/**
--------^
     2 | * General Utilities
     3 | * original author: Garry Flemings

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
