### ISSUE TITLE
Issue running node server on Codeship CI, "requireDollarBeforejQueryAssignment"

### ISSUE THREAD

**Issue by skabbes** [jscs-dev/node-jscs#2094]
```
Error running rule requireDollarBeforejQueryAssignment: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'name' of undefined
at Object.<anonymous> (/home/rof/src/github.com/brightsolar/api/node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:130:53)
at Array.forEach (native)
at Object.JsFile.iterateNodesByType (/home/rof/src/github.com/brightsolar/api/node_modules/jscs/lib/js-file.js:595:42)
at Object.module.exports.check (/home/rof/src/github.com/brightsolar/api/node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:72:14)
at null.<anonymous> (/home/rof/src/github.com/brightsolar/api/node_modules/jscs/lib/string-checker.js:165:22)
at Array.forEach (native)
at StringChecker._checkJsFile (/home/rof/src/github.com/brightsolar/api/node_modules/jscs/lib/string-checker.js:161:31)
at StringChecker.checkString (/home/rof/src/github.com/brightsolar/api/node_modules/jscs/lib/string-checker.js:106:14)
at null.<anonymous> (/home/rof/src/github.com/brightsolar/api/node_modules/jscs/lib/checker.js:56:21)
at Array.<anonymous> (/home/rof/src/github.com/brightsolar/api/node_modules/vow/lib/vow.js:712:39) at
```

The lint runs successfully locally, but fails on codeship CI.

**Comment by hzoo** [comment]
There isn't enough information here - what version of jscs are you running? If it passes locally it might be something to do with `node_modules` either locally or on CI (maybe clear the cache). A code snippet that causes this would help (if this is a bug)

**Comment by skabbes** [comment]
Hey sorry,

The output asked me to post a new issue here, so I did - partially hoping that this was a common issue, and hoping to help triage. After some more debuggin it **does** happen on both CI and locally.

This seems to be the minimal repro:

```javascript
let a = null;
let b = null;

[a, b] = [1, 2];
```

Sorry for the weak bug report, hope this helps.

**Comment by hzoo** [comment]
Ok great! All that's necessary is the version, the code that errors, and the rule.

**Comment by markelog** [comment]
> cc @markelog we should modify the https://github.com/jscs-dev/node-jscs/issues/new url to pre-fill with an issue template.

:+1:

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
