### ISSUE TITLE
requireDollarBeforejQueryAssignment internal error

### ISSUE THREAD

**Issue by decademoon** [jscs-dev/node-jscs#2118]
```
jscs results in errors
  internalError @ line 1 char 0
    Error running rule requireDollarBeforejQueryAssignment: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'name' of undefined
  at Object.<anonymous> (/Users/a/b/node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:130:53)
  at Array.forEach (native)
  at Object.JsFile.iterateNodesByType (/Users/a/b/node_modules/jscs/lib/js-file.js:595:42)
  at Object.module.exports.check (/Users/a/b/node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:72:14)
  at [object Object].<anonymous> (/Users/a/b/node_modules/jscs/lib/string-checker.js:165:22)
  at Array.forEach (native)
  at [object Object].StringChecker._checkJsFile (/Users/a/b/node_modules/jscs/lib/string-checker.js:161:31)
  at [object Object].StringChecker.checkString (/Users/a/b/node_modules/jscs/lib/string-checker.js:106:14)
  at Object.checkSource (/Users/a/b/node_modules/jscs-loader/index.js:91:24)
  at Object.<anonymous> (/Users/a/b/node_modules/jscs-loader/index.js:140:19)
  at /Users/a/b/node_modules/jscs-loader/index.js:62:7
  at tryToString (fs.js:414:3)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

**Comment by hzoo** [comment]
Thanks for the report! This looks to be the same as https://github.com/jscs-dev/node-jscs/issues/2118

**Comment by ambethia** [comment]
This _is_ #2118

**Comment by hzoo** [comment]
Oops I meant #2094 (just searched in the issues for that)
