### ISSUE TITLE
AssertionError: Unable to add an error, `column` should be a positive number but -4 given

### ISSUE THREAD

**Issue by Arcanemagus** [jscs-dev/node-jscs#2145]
When linting this code on `jscs` v2.10.1 with the `google` preset:

```js
var foo = {
  bar = 42
};
```

The following error is thrown:
```text
AssertionError: Unable to add an error, `column` should be a positive number but -4 given
    at Object.Errors._validateInput (C:\Users\Landon\AppData\Roaming\npm\node_modules\jscs\lib\errors.js:73:9)
    at Object.Errors.add (C:\Users\Landon\AppData\Roaming\npm\node_modules\jscs\lib\errors.js:46:14)
    at StringChecker._addParseError (C:\Users\Landon\AppData\Roaming\npm\node_modules\jscs\lib\string-checker.js:211:16)
    at null.<anonymous> (C:\Users\Landon\AppData\Roaming\npm\node_modules\jscs\lib\string-checker.js:97:22)
    at Array.forEach (native)
    at StringChecker.checkString (C:\Users\Landon\AppData\Roaming\npm\node_modules\jscs\lib\string-checker.js:95:31)
    at null.<anonymous> (C:\Users\Landon\AppData\Roaming\npm\node_modules\jscs\lib\checker.js:56:21)
    at Array.<anonymous> (C:\Users\Landon\AppData\Roaming\npm\node_modules\jscs\node_modules\vow\lib\vow.js:712:39)
    at Immediate.callFns [as _onImmediate] (C:\Users\Landon\AppData\Roaming\npm\node_modules\jscs\node_modules\vow\lib\vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Looking over the closed bugs here, this looks to be a `validateIndentation` bug, so CC @mikesherov.

If you need any further information please let me know. This was originally filed as https://github.com/AtomLinter/linter-jscs/issues/193.

----

System info:
`jscs`: v2.10.1
Node: v5.5.0
OS: Windows 10 x64

![image](https://cloud.githubusercontent.com/assets/427137/13243483/fcc6e834-d9b3-11e5-986d-e716d36eefa4.png)

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
