### ISSUE TITLE
Internal error, AssertionError: Unable to add an error, `column` should be a positive number but -1 given

### ISSUE THREAD

**Issue by Prairie-Falcon** [jscs-dev/node-jscs#2190]
Probable duplicate of #2145. (Didn't see that one before posting; regrets.)
Following their good lead:
- Windows 10 Home, 64-bit, version 1511 (OS Build 10586.164)
- Node v5.7.0
- JSCS v2.11.0

No complaints; I hope this helps. Anonymized a bit. The first report on this run was for disallowCapitalizedComments (at the same location in my source). This was the second report.

    internalError: Error running rule jsDoc: This is an issue with JSCS and not your codebase.
    Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
    AssertionError: Unable to add an error, `column` should be a positive number but -1 given
        at Object.Errors._validateInput (C:\Users\...\AppData\Roaming\npm\node_modules\jscs\lib\errors.js:73:9)
        at Object.Errors.add (C:\Users\...\AppData\Roaming\npm\node_modules\jscs\lib\errors.js:46:14)
        at addError (C:\Users\...\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:166:28)
        at C:\Users\...\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:181:25
        at Object.requireReturnTypes (C:\Users\...\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc\require-return-types.js:17:9)
        at C:\Users\...\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:145:27
        at Array.forEach (native)
        at DocComment.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:144:46)
        at Array.forEach (native)
        at DocComment.forEachTag [as iterate] (C:\Users\...\AppData\Roaming\npm\node_modules\jscs\node_modules\jscs-jsdoc\lib\jsdoc.js:86:19) at test.js :
         1 |/*******************************************************************************
    --------^
         2 | * <comment>
         3 | * <comment>

Thanks for doing this valuable and interesting project!

**Comment by louisch** [comment]
I am getting a similar error, and what seems to trigger it is an `@returns` block, which is missing its type. Funnily enough, I can put this on any JSDoc comment in the tab, and it will trigger this error.

e.g.
```
/**
 * <summary>
 *
 * @return <comment>
```

(Not `@return {type} <comment>`)

**Comment by markelog** [comment]
Should work with 3.x

**Comment by zxqfox** [comment]
Huh, we definitely missing tests for jsdoc... ;-(

**Comment by markelog** [comment]
So is this still valid?

**Comment by zxqfox** [comment]
Guess, yes. I'll try to look at it tomorrow.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.

You however open ticket on https://github.com/jscs-dev/jscs-jsdoc and keep pinging @zxqfox
