### ISSUE TITLE
internalError: Error running rule requireObjectKeysOnNewLine

### ISSUE THREAD

**Issue by oliversalzburg** [jscs-dev/node-jscs#2236]
```
$ jscs index.js
internalError: Error running rule requireObjectKeysOnNewLine: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'getLastToken' of undefined
    at Object.JsFile.getLastNodeToken (C:\Users\OliverSalzburg\core-mq\node_modules\jscs\lib\js-file.js:168:20)
    at Object.<anonymous> (C:\Users\OliverSalzburg\core-mq\node_modules\jscs\lib\rules\require-object-keys-on-new-line.js:102:39)
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (C:\Users\OliverSalzburg\core-mq\node_modules\jscs\lib\js-file.js:331:42)
    at Object.module.exports.check (C:\Users\OliverSalzburg\core-mq\node_modules\jscs\lib\rules\require-object-keys-on-new-line.js:85:14)
    at [object Object].<anonymous> (C:\Users\OliverSalzburg\core-mq\node_modules\jscs\lib\string-checker.js:154:22)
    at Array.forEach (native)
    at [object Object].StringChecker._checkJsFile (C:\Users\OliverSalzburg\core-mq\node_modules\jscs\lib\string-checker.js:150:31)
    at [object Object].StringChecker.checkString (C:\Users\OliverSalzburg\core-mq\node_modules\jscs\lib\string-checker.js:92:14)
    at [object Object].<anonymous> (C:\Users\OliverSalzburg\core-mq\node_modules\jscs\lib\checker.js:56:21) at index.js :
     1 |"use strict";
--------^
     2 |
     3 |module.exports = {


1 code style error found.
```

The file `index.js`:
```js
"use strict";

module.exports = {
	get exchange() {
		return require( "./lib/exchange" );
	},

	get mock() {
		return require( "./lib/mock" );
	},

	get queues() {
		return require( "./lib/queues" );
	}
};
```

Our `.jscsrc`:
```json
{
	"maxErrors": null,
	"disallowEmptyBlocks": true,
	"disallowKeywordsOnNewLine": [
		"catch",
		"else"
	],
	"disallowMixedSpacesAndTabs": "smart",
	"disallowMultipleLineStrings": true,
	"disallowMultipleVarDecl": true,
	"disallowNewlineBeforeBlockStatements": true,
	"disallowOperatorBeforeLineBreak": [
		"."
	],
	"disallowQuotedKeysInObjects": true,
	"disallowSpaceAfterKeywords": [
		"if",
		"for",
		"while",
		"do",
		"switch",
		"catch"
	],
	"disallowSpaceAfterPrefixUnaryOperators": true,
	"disallowSpaceBeforeComma": true,
	"disallowSpaceBeforePostfixUnaryOperators": [
		"++",
		"--"
	],
	"disallowSpaceBeforeSemicolon": true,
	"disallowSpacesInCallExpression": true,
	"disallowSpacesInFunction": {
		"beforeOpeningRoundBrace": true
	},
	"disallowTrailingComma": true,
	"disallowTrailingWhitespace": true,
	"requireAlignedObjectValues": "ignoreLineBreak",
	"requireBlocksOnNewline": true,
	"requireCamelCaseOrUpperCaseIdentifiers": true,
	"requireCapitalizedComments": {
		"allExcept": [
			"globals",
			"jshint",
			"noinspection"
		]
	},
	"requireCapitalizedConstructors": true,
	"requireCommaBeforeLineBreak": true,
	"requireCurlyBraces": [
		"if",
		"else",
		"for",
		"while",
		"do",
		"try",
		"catch"
	],
	"requireDotNotation": true,
	"requireFunctionDeclarations": true,
	"requireLineBreakAfterVariableAssignment": true,
	"requireLineFeedAtFileEnd": true,
	"requireNamedUnassignedFunctions": {
		"allExcept": [
			"describe",
			"it",
			"before",
			"after",
			"beforeEach",
			"afterEach"
		]
	},
	"requireNumericLiterals": true,
	"requireObjectKeysOnNewLine": true,
	"requireOperatorBeforeLineBreak": true,
	"requirePaddingNewLinesAfterUseStrict": true,
	"requirePaddingNewLinesBeforeExport": true,
	"requirePaddingNewLinesInObjects": true,
	"requireParenthesesAroundIIFE": true,
	"requireSemicolons": true,
	"requireSpaceAfterBinaryOperators": true,
	"requireSpaceAfterKeywords": [
		"else",
		"case",
		"try",
		"void",
		"with",
		"return",
		"typeof"
	],
	"requireSpaceAfterLineComment": {
		"allExcept": [
			"#",
			"=",
			"noinspection"
		]
	},
	"requireSpaceBeforeBinaryOperators": true,
	"requireSpaceBeforeBlockStatements": true,
	"requireSpaceBeforeKeywords": [
		"else",
		"while",
		"catch"
	],
	"requireSpaceBeforeObjectValues": true,
	"requireSpaceBetweenArguments": true,
	"requireSpacesInConditionalExpression": true,
	"requireSpacesInForStatement": true,
	"requireSpacesInFunction": {
		"beforeOpeningCurlyBrace": true
	},
	"requireSpacesInsideBrackets": true,
	"requireSpacesInsideParentheses": {
		"all": true
	},
	"safeContextKeyword": [
		"self"
	],
	"validateLineBreaks": "LF",
	"validateParameterSeparator": ", ",
	"validateQuoteMarks": "\""
}
```

**Comment by markelog** [comment]
What version?

**Comment by oliversalzburg** [comment]
@markelog 3.0.3
