### ISSUE TITLE
Error after upgrading jscs-jsdoc from 1.3.1 to 2.0.0

### ISSUE THREAD

**Issue by ErisDS** [jscs-dev/node-jscs#2238]
Greenkeeper just sent a PR to upgrade jscs-jsdoc from version 1.3.1 to 2.0.0. Our repo is using grunt-jscs 2.8.0, which in turn I think uses node-jscs 2.11.0

I wouldn't be raising this issue here, except that the error message tells me to! We're getting 50 code style errors reported all like the one below. I see this project is merging with eslint, and that `grunt-jscs` is a bit behind, so perhaps we need to pin something until the merge is complete?

```
Error running rule jsDoc: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Object #<Object> has no method 'getFirstToken'
  at findDocCommentBeforeNode (/Users/hannah/Ghost/Ghost/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:265:24)
  at Object.getJsdoc (/Users/hannah/Ghost/Ghost/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:237:19)
  at Object.validateCheckParamNames (/Users/hannah/Ghost/Ghost/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc/check-param-names.js:14:14)
  at /Users/hannah/Ghost/Ghost/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:128:27
  at Array.forEach (native)
  at Object.<anonymous> (/Users/hannah/Ghost/Ghost/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:127:32)
  at Array.forEach (native)
  at Object.JsFile.iterateNodesByType (/Users/hannah/Ghost/Ghost/node_modules/grunt-jscs/node_modules/jscs/lib/js-file.js:595:42)
  at /Users/hannah/Ghost/Ghost/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:120:18
  at Array.forEach (native)
  at Object.module.exports.check (/Users/hannah/Ghost/Ghost/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:112:29)
  at [object Object].<anonymous> (/Users/hannah/Ghost/Ghost/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:165:22)
  at Array.forEach (native)
  at [object Object].StringChecker._checkJsFile (/Users/hannah/Ghost/Ghost/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:161:31)
  at [object Object].StringChecker.checkString (/Users/hannah/Ghost/Ghost/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:106:14)
  at [object Object].<anonymous> (/Users/hannah/Ghost/Ghost/node_modules/grunt-jscs/node_modules/jscs/lib/checker.js:56:21)
  at Array.45 (/Users/hannah/Ghost/Ghost/node_modules/grunt-jscs/node_modules/vow/lib/vow.js:712:39)
  at Object.callFns [as _onImmediate] (/Users/hannah/Ghost/Ghost/node_modules/grunt-jscs/node_modules/vow/lib/vow.js:23:35)
  at processImmediate [as _immediateCallback] (timers.js:363:15)
 at core/server/data/import/index.js :
```

**Comment by markelog** [comment]
jscs-doc is included to jscs, so just remove it from the deps

**Comment by ErisDS** [comment]
Thanks @markelog 👍
