### ISSUE TITLE
TypeError: Cannot read property 'offset' of undefined

### ISSUE THREAD

**Issue by avighier** [jscs-dev/node-jscs#2247]
internalError: Error running rule jsDoc: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'offset' of undefined
    at Object.enforceExistence (D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc\enforce-existence.js:116:65)
    at D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:128:27
    at Array.forEach (native)
    at Object.<anonymous> (D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:127:32)
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (D:\devs\subtitles\node_modules\jscs\lib\js-file.js:331:42)
    at D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:120:18
    at Array.forEach (native)
    at Object.module.exports.check (D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:112:29)
    at .<anonymous> (D:\devs\subtitles\node_modules\jscs\lib\string-checker.js:154:22) at ./xxx.js :
     1 |var assert = require('assert');

**Comment by zxqfox** [comment]
@avighier Can you please provide information about your `xxx.js`?

**Comment by avighier** [comment]
Hi,

It was only a test for comments.

the .jscsrc :
{
    "preset": "node-style-guide",
        "jsDoc": {
                "checkAnnotations": "closurecompiler",
                "checkTypes": "strictNativeCase",
                "enforceExistence": "exceptExports"
    }
}

**Comment by avighier** [comment]
The file is "./subtitle.js"

Its code is here : https://github.com/avighier/subtitles/blob/develop/subtitle.js

**Comment by avighier** [comment]
Note that I am on Windows and I have not a well configuration. I have tabs instead of space and \r\n for line feed. The tool need, when it will be installed, to fail the build if there is that.

For the moment, the file is like that : "'var assert = require(\'assert\');\r\n\r\n/**\r\n\t@constructor\r\n\t@"

**Comment by avighier** [comment]
It seems to be that. I have replaced line feed in subtitle.js, now I have :

internalError: Error running rule jsDoc: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'offset' of undefined
    at Object.enforceExistence (D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc\enforce-existence.js:116:65)
    at D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:128:27
    at Array.forEach (native)
    at Object.<anonymous> (D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:127:32)
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (D:\devs\subtitles\node_modules\jscs\lib\js-file.js:331:42)
    at D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:120:18
    at Array.forEach (native)
    at Object.module.exports.check (D:\devs\subtitles\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:112:29)
    at .<anonymous> (D:\devs\subtitles\node_modules\jscs\lib\string-checker.js:154:22) at ./subtitles.js :
     1 |var Subtitle = require('./subtitle'),
--------^
     2 | assert = require('assert');
     3 |

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.

You however open ticket on https://github.com/jscs-dev/jscs-jsdoc and keep pinging @zxqfox
