### ISSUE TITLE
Error running rule disallowQuotedKeysInObjects

### ISSUE THREAD

**Issue by gocreating** [jscs-dev/node-jscs#2249]
![image](https://cloud.githubusercontent.com/assets/5002343/15222834/0e324cb0-18a4-11e6-82ec-9c5441c2edd4.png)

```
Error running rule disallowQuotedKeysInObjects: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'type' of undefined
    at C:\Users\go-creating\.atom\packages\linter-jscs\node_modules\jscs\lib\rules\disallow-quoted-keys-in-objects.js:72:24
    at Array.forEach (native)
    at Object. (C:\Users\go-creating\.atom\packages\linter-jscs\node_modules\jscs\lib\rules\disallow-quoted-keys-in-objects.js:70:29)
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (C:\Users\go-creating\.atom\packages\linter-jscs\node_modules\jscs\lib\js-file.js:331:42)
    at Object.module.exports.check (C:\Users\go-creating\.atom\packages\linter-jscs\node_modules\jscs\lib\rules\disallow-quoted-keys-in-objects.js:69:14)
    at [object Object]. (C:\Users\go-creating\.atom\packages\linter-jscs\node_modules\jscs\lib\string-checker.js:154:22)
    at Array.forEach (native)
    at [object Object].StringChecker._checkJsFile (C:\Users\go-creating\.atom\packages\linter-jscs\node_modules\jscs\lib\string-checker.js:150:31)
    at [object Object].StringChecker.checkString (C:\Users\go-creating\.atom\packages\linter-jscs\node_modules\jscs\lib\string-checker.js:92:14)
    at Object.lint (C:/Users/go-creating/.atom/packages/linter-jscs/src/linter-jscs.js:167:14)
    at promises.push.Promise.then._this.emitter.emit.linter (C:/Users/go-creating/.atom/packages/linter/lib/linter-registry.js:63:26)
    at C:/Users/go-creating/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (C:/Users/go-creating/.atom/packages/linter/lib/linter-registry.js:60:18)
    at file:///C:/Users/go-creating/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\go-creating\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\go-creating\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:/Users/go-creating/.atom/packages/linter/lib/editor-linter.js:80:22
    at file:///C:/Users/go-creating/.atom/packages/linter/lib/helpers.coffee:23:18at line 1 col 1
```

#### `.jscsrc`
```
{
  "preset": "node-style-guide",
  "fileExtensions": [".js"],
  "excludeFiles": [
    "node_modules/**",
    "build/**"
  ],
  "maximumLineLength": {
    "value": 80,
    "allExcept": ["comments", "urlComments", "require"]
  },
  "requireCapitalizedComments": null,
  "requireSemicolons": true,
  "validateQuoteMarks": null,
  "validateLineBreaks": null
}
```

**Comment by markelog** [comment]
What version do you use? Also need a code example

**Comment by gocreating** [comment]
@markelog I met the problem in atom's package `linter-jscs@4.0.0`. It seems using `node-jscs@3.0.3`.

Here is the broken code in the screenshot: [userReducer.js](https://github.com/gocreating/express-react-hmr-boilerplate/blob/8ff61b902e5b5bfcb2b78ae81d0b58e3f6601eb5/src%2Fcommon%2Freducers%2FuserReducer.js)

**Comment by markelog** [comment]
So i see - you using spread operator which is es7 feature, need to add support for it in cst first - https://github.com/cst/cst/issues/114
