### ISSUE TITLE
v1.9.0: AssertionError: Unable to add an error, `column` should be a positive number but -2 given

### ISSUE THREAD

**Issue by lencioni** [jscs-dev/node-jscs#857]
Hi, I just updated to 1.9.0 and when running JSCS on my code I get the following error:
```
AssertionError: Unable to add an error, `column` should be a positive number but -2 given
    at Object.Errors.add (/path/to/project/node_modules/jscs/lib/errors.js:43:9)
    at /path/to/project/node_modules/jscs/lib/rules/validate-indentation.js:102:32
    at Array.forEach (native)
    at checkIndentations (/path/to/project/node_modules/jscs/lib/rules/validate-indentation.js:95:26)
    at Object.module.exports.check (/path/to/project/node_modules/jscs/lib/rules/validate-indentation.js:330:9)
    at null.<anonymous> (/path/to/project/node_modules/jscs/lib/string-checker.js:110:22)
    at Array.forEach (native)
    at StringChecker.checkString (/path/to/project/node_modules/jscs/lib/string-checker.js:108:35)
    at null.<anonymous> (/path/to/project/node_modules/jscs/lib/checker.js:40:25)
    at Array.69 (/path/to/project/node_modules/jscs/node_modules/vow/lib/vow.js:699:39)
```

Here's my .jscsrc:

```json
{
  "fileExtensions": [".js", ".jsx"],
  "esnext": true,
  "esprima": "esprima-fb",

  "requireCurlyBraces": [
    "if",
    "else",
    "for",
    "while",
    "do",
    "try",
    "catch"
  ],

  "requireSpaceAfterKeywords": [
    "do",
    "for",
    "if",
    "else",
    "switch",
    "case",
    "try",
    "void",
    "while",
    "with",
    "return",
    "typeof"
  ],

  "disallowSpaceAfterKeywords": [
    "catch"
  ],

  "requireSpaceBeforeBlockStatements": true,
  "requireParenthesesAroundIIFE": true,

  "requireSpacesInConditionalExpression": {
    "afterTest": true,
    "beforeConsequent": true,
    "afterConsequent": true,
    "beforeAlternate": true
  },

  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningCurlyBrace": true
  },

  "requireSpacesInNamedFunctionExpression": {
    "beforeOpeningCurlyBrace": true
  },

  "requireSpacesInFunctionDeclaration": {
    "beforeOpeningCurlyBrace": true
  },

  "requireSpacesInFunction": {
    "beforeOpeningCurlyBrace": true
  },

  "disallowSpacesInCallExpression": true,
  "requireBlocksOnNewline": true,
  "disallowPaddingNewlinesInBlocks": true,
  "disallowEmptyBlocks": true,
  "disallowSpaceAfterObjectKeys": true,
  "requireSpaceBeforeObjectValues": true,
  "requireCommaBeforeLineBreak": true,

  "requireOperatorBeforeLineBreak": [
    "?",
    "=",
    "+",
    "-",
    "/",
    "*",
    "==",
    "===",
    "!=",
    "!==",
    ">",
    ">=",
    "<",
    "<="
  ],

  "disallowSpaceAfterPrefixUnaryOperators": ["++", "--", "+", "-", "~", "!"],
  "disallowSpaceBeforePostfixUnaryOperators": ["++", "--"],

  "requireSpaceBeforeBinaryOperators": [
    "=",
    "+",
    "-",
    "/",
    "*",
    "==",
    "===",
    "!=",
    "!=="
  ],

  "requireSpaceAfterBinaryOperators": [
    "=",
    ",",
    "+",
    "-",
    "/",
    "*",
    "==",
    "===",
    "!=",
    "!=="
  ],

  "requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties",
  "disallowMultipleLineStrings": true,
  "disallowMultipleLineBreaks": true,
  "disallowMixedSpacesAndTabs": true,
  "disallowTrailingWhitespace": true,
  "disallowKeywordsOnNewLine": ["else"],
  "requireCapitalizedConstructors": true,
  "requireDotNotation": true,
  "disallowYodaConditions": true,
  "requireSpaceAfterLineComment": true,
  "disallowNewlineBeforeBlockStatements": true,
  "validateLineBreaks": "LF",
  "validateQuoteMarks": { "mark": "'", "escape": true },
  "validateIndentation": 2,
  "validateParameterSeparator": ", "
}
```

I traced it down to this block of code in a file:

```js
/* jshint ignore:start */
// jscs:disable
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
// jscs:enable
/* jshint ignore:end */
```

Oddly, if I remove the first line break in the minified code block, the problem seems to go away:

```js
/* jshint ignore:start */
// jscs:disable
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
// jscs:enable
/* jshint ignore:end */
```

**Comment by mikesherov** [comment]
Just an update here. This bug highlights a flaw in the indentation engine that I've been just working around for a while that I'm now tackling in the proper way. So thanks for the nudge with submitting this issue.
