### ISSUE TITLE
requireMultipleVarDecl `true` (or consecutive throws an error) inside switch cases

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#916]
```
scanEscapeSequence: function (checks) {
    var allowNewLine = false;
    var jump = 1;
    this.skip();
    var char = this.peek();

    switch (char) {
    case "'":
      this.triggerAsync("warning", {
        code: "W114",
        line: this.line,
        character: this.char,
        data: [ "\\'" ]
      }, checks, function () {return state.jsonMode; });
      break;
    case "b":
      char = "\\b";
      break;
    case "f":
      char = "\\f";
      break;
    case "n":
      char = "\\n";
      break;
    case "r":
      char = "\\r";
      break;
    case "t":
      char = "\\t";
      break;
    case "0":
      char = "\\0";

      // Octal literals fail in strict mode.
      // Check if the number is between 00 and 07.
      var n = parseInt(this.peek(1), 10);
      this.triggerAsync("warning", {
        code: "W115",
        line: this.line,
        character: this.char
      }, checks,
      function () { return n >= 0 && n <= 7 && state.directive["use strict"]; });
      break;
    case "u":
      char = String.fromCharCode(parseInt(this.input.substr(1, 4), 16));
      jump = 5;
      break;
    case "v":
      this.triggerAsync("warning", {
        code: "W114",
        line: this.line,
        character: this.char,
        data: [ "\\v" ]
      }, checks, function () { return state.jsonMode; });

      char = "\v";
      break;
    case "x":
      var  x = parseInt(this.input.substr(1, 2), 16);

      this.triggerAsync("warning", {
        code: "W114",
        line: this.line,
        character: this.char,
        data: [ "\\x-" ]
      }, checks, function () { return state.jsonMode; });

      char = String.fromCharCode(x);
      jump = 3;
      break;
    case "\\":
      char = "\\\\";
      break;
    case "\"":
      char = "\\\"";
      break;
    case "/":
      break;
    case "":
      allowNewLine = true;
      char = "";
      break;
    }

    return { char: char, jump: jump, allowNewLine: allowNewLine };
  }
```

reports:

```
jscs src/lex.js 
TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:8:24
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/usr/local/lib/node_modules/jscs/lib/js-file.js:322:42)
    at Object.consecutive [as _check] (/usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:4:10)
    at Object.module.exports.check (/usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:86:28)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/string-checker.js:110:22)
    at Array.forEach (native)
    at StringChecker.checkString (/usr/local/lib/node_modules/jscs/lib/string-checker.js:108:35)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/checker.js:40:25)
    at Array.0 (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:699:39)
```

It looks like `parentCollection`, which is only used by this one rule may be being populated incorrectly...

**Comment by schlueter** [comment]
Although effectively useless code, a simpler case that seems to fail with the same issue is:
```javascript
switch (a) {
case "0":
  var n = 0;
}
```

```shell
$ jscs requireMultipleVarDecl-breaks-on-switch.js                                                                                                [22:09:06]
TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:41:24
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/usr/local/lib/node_modules/jscs/lib/js-file.js:328:42)
    at Object.consecutive [as _check] (/usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:37:10)
    at Object.module.exports.check (/usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:119:28)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/string-checker.js:121:22)
    at Array.forEach (native)
    at StringChecker.checkString (/usr/local/lib/node_modules/jscs/lib/string-checker.js:119:35)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/checker.js:40:25)
    at Array.0 (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:699:39)
```

I'm not sure why the specific line numbers are off, I am running this against master (f69bed2) though.

**Comment by schlueter** [comment]
While debugging this I found that this rule doesn't see multiple variable declarations in switch cases, i.e:

    switch (a) {
    case "":
      var n;
      var m;
    }

doesn't get caught. This is probably related to it not functioning. It can be made to not have an exception by checking that the sibling to test against is not undefined which is a result of the parentCollection being [ undefined ] which means that the index of the current token is -1 and it's sibling is the undefined value in parentCollection.

**Comment by mikesherov** [comment]
@schlueter thanks a bunch for debugging this issue! Would you like to take a crack at fixing it?

**Comment by kevincennis** [comment]
Different path to repro, but this also throws the same error:

```
export foo = 'foo';
export bar = 'bar';
export baz = 'baz';
```

```
TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/jscs/lib/rules/require-multiple-var-decl.js:41:24
```

**Comment by twolfson** [comment]
I mentioned this in #1163 but I should mention it here as well. I believe #916 (this issue) and #1163 are duplicates. I have opened a PR to solve the problem at its root:

#1243
